package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AcademicGrades generated by hbm2java
 */
@Entity
@Table(name = "academic_grades")
public class AcademicGrades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long acedamicGradeId;
	@JsonManagedReference
	private AcademicPerformance academicPerformance;
	private String acedamicGradeName;
	private int scoreFrom;
	private int scoreTo;
	@Transient
	private String academicId;

	public AcademicGrades() {
	}

	public AcademicGrades(long acedamicGradeId,
			AcademicPerformance academicPerformance, String acedamicGradeName,
			int scoreFrom, int scoreTo) {
		this.acedamicGradeId = acedamicGradeId;
		this.academicPerformance = academicPerformance;
		this.acedamicGradeName = acedamicGradeName;
		this.scoreFrom = scoreFrom;
		this.scoreTo = scoreTo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "acedamic_grade_id", unique = true, nullable = false)
	public long getAcedamicGradeId() {
		return this.acedamicGradeId;
	}

	public void setAcedamicGradeId(long acedamicGradeId) {
		this.acedamicGradeId = acedamicGradeId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "academic_id", nullable = false)
	public AcademicPerformance getAcademicPerformance() {
		return this.academicPerformance;
	}

	public void setAcademicPerformance(AcademicPerformance academicPerformance) {
		this.academicPerformance = academicPerformance;
	}

	@Column(name = "acedamic_grade_name", nullable = false, length = 20)
	public String getAcedamicGradeName() {
		return this.acedamicGradeName;
	}

	public void setAcedamicGradeName(String acedamicGradeName) {
		this.acedamicGradeName = acedamicGradeName;
	}

	@Column(name = "score_from", nullable = false)
	public int getScoreFrom() {
		return this.scoreFrom;
	}

	public void setScoreFrom(int scoreFrom) {
		this.scoreFrom = scoreFrom;
	}

	@Column(name = "score_to", nullable = false)
	public int getScoreTo() {
		return this.scoreTo;
	}

	public void setScoreTo(int scoreTo) {
		this.scoreTo = scoreTo;
	}

	@Transient
	public String getAcademicId() {
		return academicId;
	}
	public void setAcademicId(String academicId) {
		this.academicId = academicId;
	}


}
