package com.lp.model;

// default package
// Generated June 30, 2017 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "academic_year")
public class AcademicYear implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long academicYearId;
	private String academicYear;
	private Date startDate;
	private Date endDate;
	private String isCurrentYear;

	public AcademicYear() {
	}

	public AcademicYear(long academicYearId) {
		this.academicYearId = academicYearId;
	}

	public AcademicYear(long academicYearId, String academicYear,
			Date startDate, Date endDate) {
		this.academicYearId = academicYearId;
		this.academicYear = academicYear;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "academic_year_id", unique = true, nullable = false)
	public long getAcademicYearId() {
		return academicYearId;
	}

	public void setAcademicYearId(long academicYearId) {
		this.academicYearId = academicYearId;
	}

	@Column(name = "academic_year")
	public String getAcademicYear() {
		return academicYear;
	}

	public void setAcademicYear(String academicYear) {
		this.academicYear = academicYear;
	}

	@Column(name = "start_date")
	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "end_date")
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "is_curren_year")
	public String getIsCurrentYear() {
		return isCurrentYear;
	}

	public void setIsCurrentYear(String isCurrentYear) {
		this.isCurrentYear = isCurrentYear;
	}
	
}
