package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activity")
public class Activity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long activityId;
	@JsonManagedReference
	private Lesson lesson;
	private String activityDesc;
	@JsonManagedReference
	private UserRegistration userRegistration;
	
	@Transient
	private boolean activitySelected; 

	public Activity() {
	}

	public Activity(long activityId) {
		this.activityId = activityId;
	}

	public Activity(long activityId, Lesson lesson, String activityDesc,
			UserRegistration userRegistration) {
		this.activityId = activityId;
		this.lesson = lesson;
		this.activityDesc = activityDesc;
		this.userRegistration = userRegistration;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "activity_id", unique = true, nullable = false)
	public long getActivityId() {
		return this.activityId;
	}

	public void setActivityId(long activityId) {
		this.activityId = activityId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "lesson_id")
	public Lesson getLesson() {
		return this.lesson;
	}

	public void setLesson(Lesson lesson) {
		this.lesson = lesson;
	}

	@Column(name = "activity_desc", length = 1000)
	public String getActivityDesc() {
		return this.activityDesc;
	}

	public void setActivityDesc(String activityDesc) {
		this.activityDesc = activityDesc;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "created_by")
	public UserRegistration getUserRegistration() {
		return userRegistration;
	}

	public void setUserRegistration(UserRegistration userRegistration) {
		this.userRegistration = userRegistration;
	}

	@Transient
	public boolean isActivitySelected() {
		return activitySelected;
	}

	public void setActivitySelected(boolean activitySelected) {
		this.activitySelected = activitySelected;
	}

}
