package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AdminTeacherReports generated by hbm2java
 */
@Entity
@Table(name = "admin_teacher_reports")
public class AdminTeacherReports implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long adminTeacherReportId;
	@JsonManagedReference
	private Teacher teacher;
	private String date;
	@JsonManagedReference
	private User user;

	public AdminTeacherReports() {
	}

	public AdminTeacherReports(long adminTeacherReportId, Teacher teacher) {
		this.adminTeacherReportId = adminTeacherReportId;
		this.teacher = teacher;
	}

	public AdminTeacherReports(long adminTeacherReportId, Teacher teacher,
			String date, User user) {
		this.adminTeacherReportId = adminTeacherReportId;
		this.teacher = teacher;
		this.date = date;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "admin_teacher_report_id", unique = true, nullable = false)
	public long getAdminTeacherReportId() {
		return this.adminTeacherReportId;
	}

	public void setAdminTeacherReportId(long adminTeacherReportId) {
		this.adminTeacherReportId = adminTeacherReportId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "teacher_id", nullable = false)
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	
	@Column(name = "date", length = 10)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_typeid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}
}
