package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AssignActivity generated by hbm2java
 */
@Entity
@Table(name = "assign_activity")
public class AssignActivity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long assignActivityId;
	@JsonManagedReference
	private Activity activity;
	@JsonManagedReference
	private ClassStatus classStatus;
	private Date assignedDate;
	@Transient
	private int score;
	@Transient
	private String academicGradeName;
	
	@Transient
	private List<StudentCompositeActivityScore> studentCompositeActivityScores;

	public AssignActivity() {
	}

	public AssignActivity(ClassStatus classStatus) {
		this.classStatus = classStatus;
	}

	public AssignActivity(Activity activity, ClassStatus classStatus,
			Date assignedDate) {
		this.activity = activity;
		this.classStatus = classStatus;
		this.assignedDate = assignedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "assign_activity_id", unique = true, nullable = false)
	public Long getAssignActivityId() {
		return this.assignActivityId;
	}

	public void setAssignActivityId(Long assignActivityId) {
		this.assignActivityId = assignActivityId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "activity_id")
	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cs_id", nullable = false)
	public ClassStatus getClassStatus() {
		return this.classStatus;
	}

	public void setClassStatus(ClassStatus classStatus) {
		this.classStatus = classStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "assigned_date", length = 10)
	public Date getAssignedDate() {
		return this.assignedDate;
	}

	public void setAssignedDate(Date assignedDate) {
		this.assignedDate = assignedDate;
	}
	
	@Transient
	public int getScore() {
		return score;
	}

	public void setScore(int score) {
		this.score = score;
	}
	
	@Transient
	public String getAcademicGradeName() {
		return academicGradeName;
	}

	public void setAcademicGradeName(String academicGradeName) {
		this.academicGradeName = academicGradeName;
	}
	
	@Transient
	public List<StudentCompositeActivityScore> getStudentCompositeActivityScores() {
		return studentCompositeActivityScores;
	}

	public void setStudentCompositeActivityScores(
			List<StudentCompositeActivityScore> studentCompositeActivityScores) {
		this.studentCompositeActivityScores = studentCompositeActivityScores;
	}
}
