package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Studentk1TestStatus generated by hbm2java
 */
@Entity
@Table(name = "assign_k1_tests")
public class AssignK1Tests implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long assignK1TestId;
	@JsonManagedReference
	private StudentAssignmentStatus studentAssignmentStatus;
	@JsonManagedReference
	private K1Sets k1Set;
	private String marksGraded;
		
	public AssignK1Tests() {
	}

	public AssignK1Tests(long assignK1TestId, StudentAssignmentStatus studentAssignmentStatus, K1Sets k1Set) {
		this.assignK1TestId = assignK1TestId;
		this.studentAssignmentStatus = studentAssignmentStatus;
		this.k1Set = k1Set;
	}
	
	public AssignK1Tests(long assignK1TestId, StudentAssignmentStatus studentAssignmentStatus,
			K1Sets k1Set,  String marksGraded) {
		this.assignK1TestId = assignK1TestId;
		this.studentAssignmentStatus = studentAssignmentStatus;
		this.k1Set = k1Set;
		this.marksGraded = marksGraded;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "assign_k1_test_id", unique = true, nullable = false)
	public long getAssignK1TestId() {
		return this.assignK1TestId;
	}

	public void setAssignK1TestId(long assignK1TestId) {
		this.assignK1TestId = assignK1TestId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "set_id", nullable = false)
	public K1Sets getk1Set() {
		return this.k1Set;
	}

	public void setK1Set(K1Sets k1Set) {
		this.k1Set = k1Set;
	}

	@Column(name = "marks_graded", length = 30)
	public String getMarksGraded() {
		return marksGraded;
	}

	public void setMarksGraded(String marksGraded) {
		this.marksGraded = marksGraded;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "student_assignment_id", nullable = false)
	public StudentAssignmentStatus getStudentAssignmentStatus() {
		return studentAssignmentStatus;
	}

	public void setStudentAssignmentStatus(
			StudentAssignmentStatus studentAssignmentStatus) {
		this.studentAssignmentStatus = studentAssignmentStatus;
	}
	
}
