package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AssignLessons generated by hbm2java
 */
@Entity
@Table(name = "assign_lessons")
public class AssignLessons implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long assignId;
	@JsonManagedReference
	private ClassStatus classStatus;
	@JsonManagedReference
	private Lesson lesson;
	private Date assignedDate;
	private Date dueDate;
	
	@Transient
	private int score;
	@Transient
	private String  academicGradeName;

	@Transient
	private List<StudentCompositeLessonScore> studentCompositeLessonScores;
	

	@Transient
	private List<LessonPaths> lessonPathses = new ArrayList<LessonPaths>(0);
	@Transient
	private boolean assessmentStatus = false;
	@Transient
	private boolean homeworkStatus = false;
	@Transient
	private List<AssignActivity> activityList = new ArrayList<AssignActivity>(0);

	public AssignLessons() {
	}

	public AssignLessons(long assignId) {
		this.assignId = assignId;
	}

	public AssignLessons(long assignId, ClassStatus classStatus, Lesson lesson,
			Date assignedDate, Date dueDate) {
		this.assignId = assignId;
		this.classStatus = classStatus;
		this.lesson = lesson;
		this.assignedDate = assignedDate;
		this.dueDate = dueDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "assign_id", unique = true, nullable = false)
	public long getAssignId() {
		return this.assignId;
	}

	public void setAssignId(long assignId) {
		this.assignId = assignId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cs_id")
	public ClassStatus getClassStatus() {
		return this.classStatus;
	}

	public void setClassStatus(ClassStatus classStatus) {
		this.classStatus = classStatus;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "lesson_id")
	public Lesson getLesson() {
		return this.lesson;
	}

	public void setLesson(Lesson lesson) {
		this.lesson = lesson;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "assigned_date", length = 10)
	public Date getAssignedDate() {
		return this.assignedDate;
	}

	public void setAssignedDate(Date assignedDate) {
		this.assignedDate = assignedDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "due_date", length = 10)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Transient
	public List<LessonPaths> getLessonPathses() {
		return lessonPathses;
	}

	public void setLessonPathses(List<LessonPaths> lessonPathses) {
		this.lessonPathses = lessonPathses;
	}

	@Transient
	public boolean isAssessmentStatus() {
		return assessmentStatus;
	}

	public void setAssessmentStatus(boolean assessmentStatus) {
		this.assessmentStatus = assessmentStatus;
	}

	@Transient
	public boolean isHomeworkStatus() {
		return homeworkStatus;
	}

	public void setHomeworkStatus(boolean homeworkStatus) {
		this.homeworkStatus = homeworkStatus;
	}

	@Transient
	public List<AssignActivity> getActivityList() {
		return activityList;
	}

	public void setActivityList(List<AssignActivity> activityList) {
		this.activityList = activityList;
	}
	@Transient
	public int getScore() {
		return score;
	}

	public void setScore(int score) {
		this.score = score;
	}
	
	@Transient
	public String getAcademicGradeName() {
		return academicGradeName;
	}

	public void setAcademicGradeName(String academicGradeName) {
		this.academicGradeName = academicGradeName;
	}
	
	@Transient
	public List<StudentCompositeLessonScore> getStudentCompositeLessonScores() {
		return studentCompositeLessonScores;
	}

	public void setStudentCompositeLessonScores(
			List<StudentCompositeLessonScore> studentCompositeLessonScores) {
		this.studentCompositeLessonScores = studentCompositeLessonScores;
	}
}
