package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * AssignmentType generated by hbm2java
 */
@Entity
@Table(name = "assignment_type")
public class AssignmentType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long assignmentTypeId;
	@NotNull
	@Size(min = 5, max = 200)
	private String assignmentType;
	private Date createDate;
	private Date changeDate;
	private String usedFor;		
	
	public AssignmentType() {
	}

	public AssignmentType(long assignmentTypeId, String assignmentType,
			Date createDate, Date changeDate) {
		this.assignmentTypeId = assignmentTypeId;
		this.assignmentType = assignmentType;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	public AssignmentType(long assignmentTypeId, String assignmentType,
			Date createDate, Date changeDate, String usedFor) {
		this.assignmentTypeId = assignmentTypeId;
		this.assignmentType = assignmentType;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "assignment_type_id", unique = true, nullable = false)
	public long getAssignmentTypeId() {
		return this.assignmentTypeId;
	}

	public void setAssignmentTypeId(long assignmentTypeId) {
		this.assignmentTypeId = assignmentTypeId;
	}

	@Column(name = "assignment_type", nullable = false, length = 300)
	public String getAssignmentType() {
		return this.assignmentType;
	}

	public void setAssignmentType(String assignmentType) {
		this.assignmentType = assignmentType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_date", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}
		
	@Column(name = "used_for", length = 300)
	public String getUsedFor() {
		return usedFor;
	}

	public void setUsedFor(String usedFor) {
		this.usedFor = usedFor;
	}	
}
