package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AssignmentQuestions generated by hbm2java
 */
@Entity
@Table(name = "assignment_questions")
public class AssignmentQuestions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long assignmentQuestionsId;
	@JsonManagedReference
	private Questions questions;
	@JsonManagedReference
	private StudentAssignmentStatus studentAssignmentStatus;
	private String answer;
	private Integer maxMarks; 
	private Integer secMarks;
	private String teacherComment;
	private String BAudioPath;
	private String BRetellpath;
	@Transient 
	private long answersBYWrongResponse;	
	@Transient 
	private long answersByRightResponse;
	@Transient 
	private float answersBYWrongResponsePercentage;	
	@Transient 
	private float answersByRightResponsePercentage;
	@Transient
	private List<FluencyMarks> fluencyMarks;
	@Transient 
	private String BAccuracyPath;
	@Transient
	private String audioData;
	@JsonBackReference
	private List<FluencyMarks> fluencyMarkResults;
	


	public AssignmentQuestions() {
	}

	public AssignmentQuestions(long assignmentQuestionsId) {
		this.assignmentQuestionsId = assignmentQuestionsId;
	}

	public AssignmentQuestions(long assignmentQuestionsId, Questions questions,
			StudentAssignmentStatus studentAssignmentStatus, String answer,
			Integer maxMarks, Integer secMarks, String teacherComment,
			String BAudioPath, String BRetellpath, Integer BCountOfErrors,Integer wordsRead) {
		this.assignmentQuestionsId = assignmentQuestionsId;
		this.questions = questions;
		this.studentAssignmentStatus = studentAssignmentStatus;
		this.answer = answer;
		this.maxMarks = maxMarks;
		this.secMarks = secMarks;
		this.teacherComment = teacherComment;
		this.BAudioPath = BAudioPath;
		this.BRetellpath = BRetellpath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "assignment_questions_id", unique = true, nullable = false)
	public long getAssignmentQuestionsId() {
		return this.assignmentQuestionsId;
	}

	public void setAssignmentQuestionsId(long assignmentQuestionsId) {
		this.assignmentQuestionsId = assignmentQuestionsId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "question_id")
	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "student_assignment_id")
	public StudentAssignmentStatus getStudentAssignmentStatus() {
		return this.studentAssignmentStatus;
	}

	public void setStudentAssignmentStatus(
			StudentAssignmentStatus studentAssignmentStatus) {
		this.studentAssignmentStatus = studentAssignmentStatus;
	}

	@Column(name = "answer", length = 1500)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "max_marks")
	public Integer getMaxMarks() {
		return this.maxMarks;
	}

	public void setMaxMarks(Integer maxMarks) {
		this.maxMarks = maxMarks;
	}

	@Column(name = "sec_marks")
	public Integer getSecMarks() {
		return this.secMarks;
	}

	public void setSecMarks(Integer secMarks) {
		this.secMarks = secMarks;
	}

	@Column(name = "teacher_comment", length = 200)
	public String getTeacherComment() {
		return this.teacherComment;
	}

	public void setTeacherComment(String teacherComment) {
		this.teacherComment = teacherComment;
	}

	@Column(name = "b_audio_path", length = 30)
	public String getBAudioPath() {
		return this.BAudioPath;
	}

	public void setBAudioPath(String BAudioPath) {
		this.BAudioPath = BAudioPath;
	}

	@Column(name = "b_retell_path", length = 45)
	public String getBRetellpath() {
		return this.BRetellpath;
	}

	public void setBRetellpath(String BRetellpath) {
		this.BRetellpath = BRetellpath;
	}

	@Transient
	public long getAnswersBYWrongResponse() {
		return answersBYWrongResponse;
	}

	public void setAnswersBYWrongResponse(long answersBYWrongResponse) {
		this.answersBYWrongResponse = answersBYWrongResponse;
	}
	@Transient
	public long getAnswersByRightResponse() {
		return answersByRightResponse;
	}

	public void setAnswersByRightResponse(long answersByRightResponse) {
		this.answersByRightResponse = answersByRightResponse;
	}
	
	@Transient
	public float getAnswersBYWrongResponsePercentage() {
		return answersBYWrongResponsePercentage;
	}

	public void setAnswersBYWrongResponsePercentage(float answersBYWrongResponsePercentage) {
		this.answersBYWrongResponsePercentage = answersBYWrongResponsePercentage;
	}
	@Transient
	public float getAnswersByRightResponsePercentage() {
		return answersByRightResponsePercentage;
	}

	public void setAnswersByRightResponsePercentage(float answersByRightResponsePercentage) {
		this.answersByRightResponsePercentage = answersByRightResponsePercentage;
	}
	@Transient
	public List<FluencyMarks> getFluencyMarks() {
		return fluencyMarks;
	}

	public void setFluencyMarks(List<FluencyMarks> fluencyMarks) {
		this.fluencyMarks = fluencyMarks;
	}
	@Transient
	public String getBAccuracyPath() {
		return BAccuracyPath;
	}

	public void setBAccuracyPath(String BAccuracyPath) {
		this.BAccuracyPath = BAccuracyPath;
	}
	@Transient
	public String getAudioData() {
		return audioData;
	}

	public void setAudioData(String audioData) {
		this.audioData = audioData;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "assignmentQuestions")
	public List<FluencyMarks> getFluencyMarkResults() {
		return fluencyMarkResults;
	}

	public void setFluencyMarkResults(List<FluencyMarks> fluencyMarkResults) {
		this.fluencyMarkResults = fluencyMarkResults;
	}
}
