package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Attendance generated by hbm2java
 */
@Entity
@Table(name = "attendance")
public class Attendance implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long attendanceId;
	@JsonManagedReference
	private Student student;
	@JsonManagedReference
	private ClassStatus classStatus;
	private Date date;
	private String status;
	private Date createDate;
	private Date changeDate;
	private String readStatus;

	public Attendance() {
	}

	public Attendance(long attendanceId, ClassStatus classStatus, Date date,
			String status, Date createDate, Date changeDate) {
		this.attendanceId = attendanceId;
		this.classStatus = classStatus;
		this.date = date;
		this.status = status;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	public Attendance(long attendanceId, Student student,
			ClassStatus classStatus, Date date, String status, Date createDate,
			Date changeDate, String readStatus) {
		this.attendanceId = attendanceId;
		this.student = student;
		this.classStatus = classStatus;
		this.date = date;
		this.status = status;
		this.createDate = createDate;
		this.changeDate = changeDate;
		this.readStatus = readStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "attendance_id", unique = true, nullable = false)
	public long getAttendanceId() {
		return this.attendanceId;
	}

	public void setAttendanceId(long attendanceId) {
		this.attendanceId = attendanceId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "student_id")
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cs_id", nullable = false)
	public ClassStatus getClassStatus() {
		return this.classStatus;
	}

	public void setClassStatus(ClassStatus classStatus) {
		this.classStatus = classStatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_date", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}
	
	@Column(name = "read_status", length = 10)
	public String getReadStatus() {
		return readStatus;
	}

	public void setReadStatus(String readStatus) {
		this.readStatus = readStatus;
	}
	
}

