package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.directwebremoting.annotations.DataTransferObject;
import org.directwebremoting.annotations.RemoteProperty;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * benchmarkDirectionss generated by hbm2java
 */
@Entity
@Table(name = "benchmark_directions")
@DataTransferObject(type = "bean", javascript = "Language")
public class BenchmarkDirections implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long benchmarkDirectionsId;
	@JsonManagedReference
	private Language language;
	private String fluencyDirections;
	private String retellDirections;

	public BenchmarkDirections() {
	}

	public BenchmarkDirections(long benchmarkDirectionsId) {
		this.benchmarkDirectionsId = benchmarkDirectionsId;
	}

	public BenchmarkDirections(long benchmarkDirectionsId, Language language,
			String fluencyDirections, String retellDirections) {
		this.benchmarkDirectionsId = benchmarkDirectionsId;
		this.language = language;
		this.fluencyDirections = fluencyDirections;
		this.retellDirections = retellDirections;
	}

	@RemoteProperty
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "benchmark_directions_id")
	public long getbenchmarkDirectionsId() {
		return this.benchmarkDirectionsId;
	}

	public void setbenchmarkDirectionsId(long benchmarkDirectionsId) {
		this.benchmarkDirectionsId = benchmarkDirectionsId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "language_id")
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@Column(name = "fluency_directions", length = 45)
	public String getFluencyDirections() {
		return fluencyDirections;
	}

	public void setFluencyDirections(String fluencyDirections) {
		this.fluencyDirections = fluencyDirections;
	}

	@Column(name = "retell_directions", length = 45)
	public String getRetellDirections() {
		return retellDirections;
	}

	public void setRetellDirections(String retellDirections) {
		this.retellDirections = retellDirections;
	}
}
