package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * BenchmarkResults generated by hbm2java
 */
@Entity
@Table(name = "benchmark_results")
public class BenchmarkResults implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long benchmarkResultsId;
	@JsonManagedReference
	private StudentAssignmentStatus studentAssignmentStatus;
	@JsonManagedReference
	private QualityOfResponse qualityOfResponse;
	private Integer medianFluencyScore;
	private Integer medianRetellScore;
	private Float accuracy;
	private String teacherNotes;

	public BenchmarkResults() {
	}

	public BenchmarkResults(long benchmarkResultsId) {
		this.benchmarkResultsId = benchmarkResultsId;
	}

	public BenchmarkResults(long benchmarkResultsId,
			StudentAssignmentStatus studentAssignmentStatus,
			QualityOfResponse qualityOfResponse, Integer medianFulencyCore,
			Integer medianRetellScore, Float accuracy, String teacherNotes) {
		this.benchmarkResultsId = benchmarkResultsId;
		this.studentAssignmentStatus = studentAssignmentStatus;
		this.qualityOfResponse = qualityOfResponse;
		this.medianFluencyScore = medianFulencyCore;
		this.medianRetellScore = medianRetellScore;
		this.accuracy = accuracy;
		this.teacherNotes = teacherNotes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "benchmark_results_id", unique = true, nullable = false)
	public long getBenchmarkResultsId() {
		return this.benchmarkResultsId;
	}

	public void setBenchmarkResultsId(long benchmarkResultsId) {
		this.benchmarkResultsId = benchmarkResultsId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "student_assignment_id")
	public StudentAssignmentStatus getStudentAssignmentStatus() {
		return this.studentAssignmentStatus;
	}

	public void setStudentAssignmentStatus(
			StudentAssignmentStatus studentAssignmentStatus) {
		this.studentAssignmentStatus = studentAssignmentStatus;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "quality_of_response_id")
	public QualityOfResponse getQualityOfResponse() {
		return this.qualityOfResponse;
	}

	public void setQualityOfResponse(QualityOfResponse qualityOfResponse) {
		this.qualityOfResponse = qualityOfResponse;
	}

	@Column(name = "median_fluency_score")
	public Integer getMedianFluencyScore() {
		return this.medianFluencyScore;
	}

	public void setMedianFluencyScore(Integer medianFluencyScore) {
		this.medianFluencyScore = medianFluencyScore;
	}
	
	@Column(name = "median_retell_score")
	public Integer getMedianRetellScore() {
		return this.medianRetellScore;
	}

	public void setMedianRetellScore(Integer medianRetellScore) {
		this.medianRetellScore = medianRetellScore;
	}

	@Column(name = "accuracy", precision = 12, scale = 0)
	public Float getAccuracy() {
		return this.accuracy;
	}

	public void setAccuracy(Float accuracy) {
		this.accuracy = accuracy;
	}

	@Column(name = "teacher_notes", length = 200)
	public String getTeacherNotes() {
		return this.teacherNotes;
	}

	public void setTeacherNotes(String teacherNotes) {
		this.teacherNotes = teacherNotes;
	}

}
