package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Citizenship generated by hbm2java
 */
@Entity
@Table(name = "citizenship")
public class Citizenship implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long citizenshipId;
	@NotNull
	@Size(min = 1, max = 20)
	private String citizenshipName;
	public Citizenship() {
	}

	public Citizenship(long citizenshipId, String citizenshipName) {
		this.citizenshipId = citizenshipId;
		this.citizenshipName = citizenshipName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Citizenship_id", unique = true, nullable = false)
	public long getCitizenshipId() {
		return this.citizenshipId;
	}

	public void setCitizenshipId(long citizenshipId) {
		this.citizenshipId = citizenshipId;
	}

	@Column(name = "Citizenship_name", nullable = false, length = 20)
	public String getCitizenshipName() {
		return this.citizenshipName;
	}

	public void setCitizenshipName(String citizenshipName) {
		this.citizenshipName = citizenshipName;
	}
}
