package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * ClassActualSchedule generated by hbm2java
 */
@Entity
@Table(name = "class_actual_schedule")
public class ClassActualSchedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long casId;
	private Periods periods;
	@JsonManagedReference
	private ClassStatus classStatus;
	@JsonManagedReference
	private Days days;

	public ClassActualSchedule() {
	}

	public ClassActualSchedule(long casId, ClassStatus classStatus, Days day) {
		this.casId = casId;
		this.classStatus = classStatus;
		this.days = day;
	}

	public ClassActualSchedule(long casId, Periods periods,
			ClassStatus classStatus, Days day) {
		this.casId = casId;
		this.periods = periods;
		this.classStatus = classStatus;
		this.days = day;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cas_id", unique = true, nullable = false)
	public long getCasId() {
		return this.casId;
	}

	public void setCasId(long casId) {
		this.casId = casId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "period_id")
	public Periods getPeriods() {
		return this.periods;
	}

	public void setPeriods(Periods periods) {
		this.periods = periods;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cs_id", nullable = false)
	public ClassStatus getClassStatus() {
		return this.classStatus;
	}

	public void setClassStatus(ClassStatus classStatus) {
		this.classStatus = classStatus;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "day_id")
	public Days getDays() {
		return this.days;
	}

	public void setDays(Days day) {
		this.days = day;
	}
}
