package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * ClassStatus generated by hbm2java
 */
@Entity
@Table(name = "class_status")
public class ClassStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long csId;
	@JsonManagedReference
	private Section section;
	@JsonManagedReference
	private Teacher teacher;
	private String availStatus;
	private String description;
	private Date startDate;
	private Date endDate;
	private String editingStatus;
	public ClassStatus() {
	}

	public ClassStatus(long csId, Section section, Teacher teacher,
			String description, Date startDate, Date endDate) {
		this.csId = csId;
		this.section = section;
		this.teacher = teacher;
		this.description = description;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public ClassStatus(long csId, Section section, Teacher teacher,
			String availStatus, String description, Date startDate,
			Date endDate, String editingStatus) {
		this.csId = csId;
		this.section = section;
		this.teacher = teacher;
		this.availStatus = availStatus;
		this.description = description;
		this.startDate = startDate;
		this.endDate = endDate;
		this.editingStatus = editingStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cs_id", unique = true, nullable = false)
	public long getCsId() {
		return this.csId;
	}

	public void setCsId(long csId) {
		this.csId = csId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "section_id", nullable = false)
	public Section getSection() {
		return this.section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "teacher_id", nullable = false)
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@Column(name = "avail_status", length = 45)
	public String getAvailStatus() {
		return this.availStatus;
	}

	public void setAvailStatus(String availStatus) {
		this.availStatus = availStatus;
	}

	@Column(name = "description", nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "editing_status", length = 45)
	public String getEditingStatus() {
		return this.editingStatus;
	}

	public void setEditingStatus(String editingStatus) {
		this.editingStatus = editingStatus;
	}
}
