package com.lp.model;

//default package
//Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* Activity generated by hbm2java
*/
@Entity
@Table(name = "fluency_error_types")
public class FluencyErrorTypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long errorTypeId;
	private String errorType;
	private String errorColor;
	
	public FluencyErrorTypes() {
	}

	public FluencyErrorTypes(long errorTypeId) {
		this.errorTypeId = errorTypeId;
	}

	public FluencyErrorTypes(long errorTypeId, String errorType,String errorColor) {
		this.errorTypeId = errorTypeId;
		this.errorType = errorType;
		this.errorColor=errorColor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "error_type_id", unique = true, nullable = false)
	public long getErrorTypeId() {
		return this.errorTypeId;
	}

	public void setErrorTypeId(long errorTypeId) {
		this.errorTypeId = errorTypeId;
	}

	@Column(name = "error_type", length = 1000)
	public String getErrorType() {
		return this.errorType;
	}

	public void setErrorType(String errorType) {
		this.errorType = errorType;
	}
	@Column(name = "error_color", length = 1000)
	public String getErrorColor() {
		return this.errorColor;
	}

	public void setErrorColor(String errorColor) {
		this.errorColor = errorColor;
	}


	}
