package com.lp.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "fluency_comments")
public class FluencyComments implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long commentId;
	private String comment;
	
	public FluencyComments() {
	}
	
	public FluencyComments(long commentId, String comment) {
		super();
		this.commentId = commentId;
		this.comment = comment;
	}

	@Id
	@Column(name = "comment_id", unique = true, nullable = false)
	public long getCommentId() {
		return commentId;
	}

	public void setCommentId(long commentId) {
		this.commentId = commentId;
	}

	@Column(name = "comment", nullable = false, length = 500)
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	
	
}
