package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Interest generated by hbm2java
 */
@Entity
@Table(name = "grading_types")
public class GradingTypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long gradingTypesId;
	private String gradingTypes;

	
	public GradingTypes() {
	}

	public GradingTypes(long gradingTypesId, String gradingTypes) {
		this.gradingTypesId = gradingTypesId;
		this.gradingTypes = gradingTypes;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "grading_type_id", unique = true, nullable = false)	
	public long getGradingTypesId() {
		return gradingTypesId;
	}

	public void setGradingTypesId(long gradingTypesId) {
		this.gradingTypesId = gradingTypesId;
	}
	@Column(name = "grading_type", unique = true, nullable = false, length = 30)
	public String getGradingTypes() {
		return gradingTypes;
	}

	public void setGradingTypes(String gradingTypes) {
		this.gradingTypes = gradingTypes;
	}

}
