package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * GradeLevel generated by hbm2java
 */
@Entity
@Table(name = "grade_level")
public class GradeLevel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long gradeLevelId;
	@NotNull
	@Size(min = 1, max = 45)
	private String gradeLevelName;
	public GradeLevel() {
	}

	public GradeLevel(long gradeLevelId, String gradeLevelName) {
		this.gradeLevelId = gradeLevelId;
		this.gradeLevelName = gradeLevelName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "grade_level_id", unique = true, nullable = false)
	public long getGradeLevelId() {
		return this.gradeLevelId;
	}

	public void setGradeLevelId(long gradeLevelId) {
		this.gradeLevelId = gradeLevelId;
	}

	@Column(name = "grade_level_name", nullable = false, length = 45)
	public String getGradeLevelName() {
		return this.gradeLevelName;
	}

	public void setGradeLevelName(String gradeLevelName) {
		this.gradeLevelName = gradeLevelName;
	}
}
