package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Gradeevents generated by hbm2java
 */
@Entity
@Table(name = "gradeevents")
public class Gradeevents implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long eventId;
	@NotNull
	@Size(min = 1, max = 20)
	private String eventName;
	private String isComposite;
	public Gradeevents() {
	}

	public Gradeevents(long eventId, String eventName, String isComposite) {
		this.eventId = eventId;
		this.eventName = eventName;
		this.isComposite = isComposite;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "event_id", unique = true, nullable = false)
	public long getEventId() {
		return this.eventId;
	}

	public void setEventId(long eventId) {
		this.eventId = eventId;
	}

	@Column(name = "event_name", nullable = false, length = 20)
	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}
	
	@Column(name = "is_composite", nullable = true, length = 5)
	public String getIsComposite() {
		return isComposite;
	}

	public void setIsComposite(String isComposite) {
		this.isComposite = isComposite;
	}
	
	
}
