package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "grade")
public class Grade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long gradeId;
	@JsonManagedReference
	private MasterGrades masterGrades;
	private long schoolId;
	private String status;
	private Date createDate;
	private Date changeDate;

	public Grade() {
	}

	public Grade(long gradeId, long schoolId, String status, Date createDate,
			Date changeDate) {
		this.gradeId = gradeId;
		this.schoolId = schoolId;
		this.status = status;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	public Grade(long gradeId, MasterGrades masterGrades, long schoolId,
			String status, Date createDate, Date changeDate) {
		this.gradeId = gradeId;
		this.masterGrades = masterGrades;
		this.schoolId = schoolId;
		this.status = status;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "grade_id", unique = true, nullable = false)
	public long getGradeId() {
		return this.gradeId;
	}

	public void setGradeId(long gradeId) {
		this.gradeId = gradeId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "master_grades_id")
	public MasterGrades getMasterGrades() {
		return this.masterGrades;
	}

	public void setMasterGrades(MasterGrades masterGrades) {
		this.masterGrades = masterGrades;
	}

	@Column(name = "school_id", nullable = false)
	public long getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(long schoolId) {
		this.schoolId = schoolId;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_date", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}
}
