package com.lp.model;

import javax.persistence.Embeddable;

// Generated May 28, 2015 3:44:36 PM by Hibernate Tools 4.0.0

/**
 * GroupPerformanceTempId generated by hbm2java
 */
@Embeddable
public class GroupPerformanceTempId implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private long performanceGroupStudentsId;
	private long assignedTaskId;

	public GroupPerformanceTempId() {
	}

	public GroupPerformanceTempId(long performanceGroupStudentsId,
			long assignedTaskId) {		
		this.performanceGroupStudentsId = performanceGroupStudentsId;
		this.assignedTaskId = assignedTaskId;
	}

	public long getPerformanceGroupStudentsId() {
		return performanceGroupStudentsId;
	}

	public void setPerformanceGroupStudentsId(long performanceGroupStudentsId) {
		this.performanceGroupStudentsId = performanceGroupStudentsId;
	}

	public long getAssignedTaskId() {
		return assignedTaskId;
	}

	public void setAssignedTaskId(long assignedTaskId) {
		this.assignedTaskId = assignedTaskId;
	}	

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupPerformanceTempId))
			return false;
		GroupPerformanceTempId castOther = (GroupPerformanceTempId) other;

		return (this.getPerformanceGroupStudentsId() == castOther
				.getPerformanceGroupStudentsId())
				&& (this.getAssignedTaskId() == castOther.getAssignedTaskId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPerformanceGroupStudentsId();
		result = 37 * result + (int) this.getAssignedTaskId();
		
		return result;
	}


}
