package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Invitations generated by hbm2java
 */
@Entity
@Table(name = "invitations")
public class Invitations implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long invitationId;
	@JsonManagedReference
	private UserRegistration userRegistration;
	@JsonManagedReference
	private User user;
	private String inviteeEmail;
	private String firstName;
	private String lastName;
	@Transient
	private String userTypeid;
	private String message;
	private Date createDate;
	private Date changeDate;

	public Invitations() {
	}

	public Invitations(long invitationId, UserRegistration userRegistration,
			String inviteeEmail, User user, Date createDate, Date changeDate) {
		this.invitationId = invitationId;
		this.userRegistration = userRegistration;
		this.inviteeEmail = inviteeEmail;
		this.user = user;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	public Invitations(long invitationId, UserRegistration userRegistration,
			String inviteeEmail, String firstName, String lastName, User user,
			String message, Date createDate, Date changeDate) {
		this.invitationId = invitationId;
		this.userRegistration = userRegistration;
		this.inviteeEmail = inviteeEmail;
		this.firstName = firstName;
		this.lastName = lastName;
		this.user = user;
		this.message = message;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "invitation_id", unique = true, nullable = false)
	public long getInvitationId() {
		return this.invitationId;
	}

	public void setInvitationId(long invitationId) {
		this.invitationId = invitationId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "reg_id", nullable = false)
	public UserRegistration getUserRegistration() {
		return this.userRegistration;
	}

	public void setUserRegistration(UserRegistration userRegistration) {
		this.userRegistration = userRegistration;
	}

	@Column(name = "invitee_email", nullable = false, length = 45)
	public String getInviteeEmail() {
		return this.inviteeEmail;
	}

	public void setInviteeEmail(String inviteeEmail) {
		this.inviteeEmail = inviteeEmail;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Transient
	public String getUserTypeid() {
		return this.userTypeid;
	}

	public void setUserTypeid(String userTypeid) {
		this.userTypeid = userTypeid;
	}

	@Column(name = "message", length = 150)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_date", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_typeid", nullable = false)
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}

}
