package com.lp.model;

// Generated Apr 15, 2015 3:45:41 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.OneToMany;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * JacQuestionFile generated by hbm2java
 */
@Entity
@Table(name = "jac_question_file")
public class JacQuestionFile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1890873104077747058L;
	private Long jacQuestionFileId;
	private String usedFor;
	@JsonManagedReference
	private UserRegistration userRegistration;
	@JsonManagedReference
	private Lesson lesson;
	private String filename;
	@JsonBackReference
	private List<JacTemplate> jacTempateList = new ArrayList<>();

	public JacQuestionFile(String usedFor, UserRegistration userRegistration,
			Lesson lesson, String filename) {
		this.usedFor = usedFor;
		this.userRegistration = userRegistration;
		this.lesson = lesson;
		this.filename = filename;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "jac_question_file_id", unique = true, nullable = false)
	public Long getJacQuestionFileId() {
		return this.jacQuestionFileId;
	}

	public void setJacQuestionFileId(Long jacQuestionFileId) {
		this.jacQuestionFileId = jacQuestionFileId;
	}

	@Column(name = "used_for")
	public String getUsedFor() {
		return usedFor;
	}

	public void setUsedFor(String usedFor) {
		this.usedFor = usedFor;
	}

	@ManyToOne
	@JoinColumn(name = "reg_id")
	public UserRegistration getUserRegistration() {
		return this.userRegistration;
	}

	public void setUserRegistration(UserRegistration userRegistration) {
		this.userRegistration = userRegistration;
	}

	@ManyToOne
	@JoinColumn(name = "lesson_id")
	public Lesson getLesson() {
		return this.lesson;
	}

	public void setLesson(Lesson lesson) {
		this.lesson = lesson;
	}

	@Column(name = "filename")
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public JacQuestionFile() {
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "jacQuestionFile")
    public List<JacTemplate> getJacTempateList() {
        return jacTempateList;
    }
	
    public void setJacTempateList(List<JacTemplate> jacTempateList) {
        this.jacTempateList = jacTempateList;
    }
}
