package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.directwebremoting.annotations.RemoteProperty;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * States generated by hbm2java
 */
@Entity
@Table(name = "learning_indicator")
public class LearningIndicator implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long learningIndicatorId;
	private Date reportDate;
	private Date createDate;
	private String status;
	@JsonManagedReference
	private LegendCriteria legendCriteria;
	private Float leScore;
	@JsonManagedReference
	private IOLReport iolReport;
	
	
	public LearningIndicator() {
	}

	public LearningIndicator(long learningIndicatorId) {
		this.learningIndicatorId = learningIndicatorId;
	}

	public LearningIndicator(long learningIndicatorId, Date reportDate,Date createDate,LegendCriteria legendCriteria,Float leScore,IOLReport iolReport) {
		this.learningIndicatorId = learningIndicatorId;
		this.reportDate = reportDate;
		this.createDate = createDate;
		this.legendCriteria=legendCriteria;
		this.leScore=leScore;
		this.iolReport=iolReport;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "learning_indicator_id", unique = true, nullable = false)
	public long getLearningIndicatorId() {
		return learningIndicatorId;
	}

	public void setLearningIndicatorId(long learningIndicatorId) {
		this.learningIndicatorId = learningIndicatorId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "report_date", length = 10)
	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	@RemoteProperty
	@Column(name = "status", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "legend_criteria_id")
	public LegendCriteria getLegendCriteria() {
		return this.legendCriteria;
	}

	public void setLegendCriteria(LegendCriteria legendCriteria) {
		this.legendCriteria = legendCriteria;
	}
	@Column(name = "le_score", length = 20)
	public Float getLeScore() {
		return this.leScore;
	}

	public void setLeScore(Float leScore) {
		this.leScore = leScore;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "iol_report_id")
	public IOLReport getIolReport() {
		return iolReport;
	}

	public void setIolReport(IOLReport iolReport) {
		this.iolReport = iolReport;
	}
	
	
}