package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * States generated by hbm2java
 */
@Entity
@Table(name = "legend_criteria")
public class LegendCriteria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long legendCriteriaId;
    private String legendCriteriaName;
	@Transient
	private List<LegendSubCriteria> legendSubCriteria;
	
	public LegendCriteria() {
	}

	public LegendCriteria(long legendCriteriaId) {
		this.legendCriteriaId = legendCriteriaId;
	}

	public LegendCriteria(long legendCriteriaId, String legendCriteriaName) {
		this.legendCriteriaId = legendCriteriaId;
		this.legendCriteriaName = legendCriteriaName;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "legend_criteria_id", unique = true, nullable = false)
	public long getLegendCriteriaId() {
		return legendCriteriaId;
	}

	public void setLegendCriteriaId(long legendCriteriaId) {
		this.legendCriteriaId = legendCriteriaId;
	}
	
	@Column(name = "legend_criteria_name", length = 20)
	public String getLegendCriteriaName() {
		return legendCriteriaName;
	}

	public void setLegendCriteriaName(String legendCriteriaName) {
		this.legendCriteriaName = legendCriteriaName;
	}
	@Transient
	public List<LegendSubCriteria> getLegendSubCriteria() {
		return legendSubCriteria;
	}

	public void setLegendSubCriteria(List<LegendSubCriteria> legendSubCriteria) {
		this.legendSubCriteria = legendSubCriteria;
	}
}
