package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.directwebremoting.annotations.RemoteProperty;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * States generated by hbm2java
 */
@Entity
@Table(name = "legend_sub_criteria")
public class LegendSubCriteria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long legendSubCriteriaId;
	@JsonManagedReference
	private LegendCriteria legendCriteria;
	private String legendSubCriteriaName;
	
	public LegendSubCriteria() {
	}

	public LegendSubCriteria(long legendSubCriteriaId) {
		this.legendSubCriteriaId = legendSubCriteriaId;
	}

	public LegendSubCriteria(long legendSubCriteriaId, LegendCriteria legendCriteria, String legendSubCriteriaName) {
		this.legendSubCriteriaId = legendSubCriteriaId;
		this.legendCriteria = legendCriteria;
		this.legendSubCriteriaName = legendSubCriteriaName;
		
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "legend_sub_criteria_id", unique = true, nullable = false)
	public long getLegendSubCriteriaId() {
		return legendSubCriteriaId;
	}

	public void setLegendSubCriteriaId(long legendSubCriteriaId) {
		this.legendSubCriteriaId = legendSubCriteriaId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "legend_criteria_id")
	public LegendCriteria getLegendCriteria() {
		return this.legendCriteria;
	}

	public void setLegendCriteria(LegendCriteria legendCriteria) {
		this.legendCriteria = legendCriteria;
	}

	@RemoteProperty
	@Column(name = "legend_sub_criteria_name", length = 100)
	public String getlegendSubCriteriaName() {
		return this.legendSubCriteriaName;
	}

	public void setlegendSubCriteriaName(String legendSubCriteriaName) {
		this.legendSubCriteriaName = legendSubCriteriaName;
	}

	
}
