package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "legend")
public class Legend implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long legendId;
	private String legendName;
	private long legendValue;
	private String color;
	private String isDefault;
	@JsonManagedReference
	private LegendSubCriteria legendSubCriteria ;
	@JsonManagedReference
	private UserRegistration createdBy;
	private String status;
	@JsonManagedReference
	private District district;
	@JsonManagedReference
	private MasterGrades fromGrade;
	@JsonManagedReference
	private MasterGrades toGrade;
	
	
	public Legend() {
	}

	public Legend(long legendId) {
		this.legendId = legendId;
	}

	public Legend(long legendId, String legendName, long legendValue,LegendSubCriteria legendSubCriteria,
			UserRegistration createdBy, String status, District district, MasterGrades fromGrade, MasterGrades toGrade) {
		this.legendId = legendId;
		this.legendName = legendName;
		this.legendValue = legendValue;
		this.legendSubCriteria = legendSubCriteria;
		this.createdBy = createdBy;
		this.status=status;
		this.district = district;
		this.fromGrade = fromGrade;
		this.toGrade = toGrade;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "legend_id", unique = true, nullable = false)
	public long getLegendId() {
		return this.legendId;
	}

	public void setLegendId(long legendId) {
		this.legendId = legendId;
	}

	@Column(name = "legend_name", length = 40)
	public String getLegendName() {
		return this.legendName;
	}

	public void setLegendName(String legendName) {
		this.legendName = legendName;
	}

	@Column(name = "legend_value")
	public long getLegendValue() {
		return legendValue;
	}

	public void setLegendValue(long legendValue) {
		this.legendValue = legendValue;
	}
	@Column(name = "color")
	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}
	@Column(name = "isdefault")
	public String getIsDefault() {
		return isDefault;
	}

	public void setIsDefault(String isDefault) {
		this.isDefault = isDefault;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "legend_sub_criteria_id")
	public LegendSubCriteria getLegendSubCriteria() {
		return this.legendSubCriteria;
	}

	public void setLegendSubCriteria(LegendSubCriteria legendSubCriteria) {
		this.legendSubCriteria = legendSubCriteria;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "created_by")
	public UserRegistration getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(UserRegistration createdBy) {
		this.createdBy = createdBy;
	}
	
	@Column(name = "status", length = 45)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "district_id")
	public District getDistrict() {
		return district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "from_grade")
	public MasterGrades getFromGrade() {
		return fromGrade;
	}

	public void setFromGrade(MasterGrades fromGrade) {
		this.fromGrade = fromGrade;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "to_grade")
	public MasterGrades getToGrade() {
		return toGrade;
	}

	public void setToGrade(MasterGrades toGrade) {
		this.toGrade = toGrade;
	}
	
	
	
}
