package com.lp.model;

//default package
//Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
* States generated by hbm2java
*/
@Entity
@Table(name = "le_rubrics")
public class LERubrics implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long leRubricId;
	@JsonManagedReference
	private Grade grade;
	@JsonManagedReference
	private LegendSubCriteria legendSubCriteria ;
	@JsonManagedReference
	private Legend legend;
	private String status;
	
	public LERubrics() {
	}

	public LERubrics(long leRubricId) {
		this.leRubricId = leRubricId;
	}

	public LERubrics(long leRubricId, Grade grade,LegendSubCriteria legendSubCriteria,Legend legend, String status) {
		this.leRubricId = leRubricId;
		this.grade = grade;
		this.legendSubCriteria = legendSubCriteria;
		this.legend=legend;
		this.status = status;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "le_rubric_id", unique = true, nullable = false)
	public long getLeRubricId() {
		return leRubricId;
	}

	public void setLeRubricId(long leRubricId) {
		this.leRubricId = leRubricId;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "grade_id")
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "legend_sub_criteria_id")
	public LegendSubCriteria getLegendSubCriteria() {
		return this.legendSubCriteria;
	}

	public void setLegendSubCriteria(LegendSubCriteria legendSubCriteria) {
		this.legendSubCriteria = legendSubCriteria;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "legend_id")
	public Legend getLegend() {
		return this.legend;
	}

	public void setLegend(Legend legend) {
		this.legend = legend;
	}
	
	@Column(name = "status", length = 45)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}
