package com.lp.model;

// default package
// Generated Jun 11, 2014 7:25:34 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Lesson generated by hbm2java
 */
@Entity
@Table(name = "lesson")
public class Lesson implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long lessonId;
	@JsonManagedReference
	private Unit unit;
	private Integer lessonNo;
	private String lessonName;
	private String lessonDesc;
	private Date createDate;
	private Date changeDate;
	@Transient
	private boolean lessonSelected;
	@JsonManagedReference
	private UserRegistration userRegistration;
	
	@Transient
	private List<Activity> activityList = new ArrayList<Activity>(0);

	public Lesson() {
	}

	public Lesson(String lessonName, Date createDate, Date changeDate) {
		this.lessonName = lessonName;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	public Lesson(Unit unit, Integer lessonNo, String lessonName,
			String lessonDesc, Date createDate, Date changeDate, UserRegistration userRegistration) {
		this.unit = unit;
		this.lessonNo = lessonNo;
		this.lessonName = lessonName;
		this.lessonDesc = lessonDesc;
		this.createDate = createDate;
		this.changeDate = changeDate;
		this.userRegistration = userRegistration;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "lesson_id", unique = true, nullable = false)
	public Long getLessonId() {
		return this.lessonId;
	}

	public void setLessonId(Long lessonId) {
		this.lessonId = lessonId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "unit_id")
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@Column(name = "lesson_no")
	public Integer getLessonNo() {
		return this.lessonNo;
	}

	public void setLessonNo(Integer lessonNo) {
		this.lessonNo = lessonNo;
	}

	@Column(name = "lesson_name", nullable = false, length = 45)
	public String getLessonName() {
		return this.lessonName;
	}

	public void setLessonName(String lessonName) {
		this.lessonName = lessonName;
	}

	@Column(name = "lesson_desc", length = 300)
	public String getLessonDesc() {
		return this.lessonDesc;
	}

	public void setLessonDesc(String lessonDesc) {
		this.lessonDesc = lessonDesc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_date", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	@Transient
	public boolean isLessonSelected() {
		return lessonSelected;
	}

	public void setLessonSelected(boolean lessonSelected) {
		this.lessonSelected = lessonSelected;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "created_by")
	public UserRegistration getUserRegistration() {
		return userRegistration;
	}

	public void setUserRegistration(UserRegistration userRegistration) {
		this.userRegistration = userRegistration;
	}
	
	@Transient
	public List<Activity> getActivityList() {
		return activityList;
	}

	public void setActivityList(List<Activity> activityList) {
		this.activityList = activityList;
	}


}
