package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.lp.utils.WebKeys;

/**
 * Days generated by hbm2java
 */
@Entity
@Table(name = "lp_news")
public class LPNews implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private long lpNewsId;
	private String title;
	private String urlLink;
	private String status;	

	public LPNews() {
	}

	public LPNews(long lpNewsId, String title, String urlLink, String status) {
		super();
		this.lpNewsId = lpNewsId;
		this.title = title;
		this.urlLink = urlLink;
		this.status = WebKeys.ACTIVE;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "lp_news_id", unique = true, nullable = false)
	public long getLpNewsId() {
		return lpNewsId;
	}

	public void setLpNewsId(long lpNewsId) {
		this.lpNewsId = lpNewsId;
	}

	@Column(name = "title", unique = true, nullable = false, length = 45)
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "url_link", unique = true, nullable = false, length = 500)
	public String getUrlLink() {
		return urlLink;
	}

	public void setUrlLink(String urlLink) {
		this.urlLink = urlLink;
	}
	
	@Column(name = "status", nullable = false, length = 45, insertable=false , updatable=true )
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	

}
