package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AcademicGrades generated by hbm2java
 */
@Entity
@Table(name = "math_gear")
public class MathGear implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long mathGearId;
	private String mathGear;

	public MathGear() {
	}

	public MathGear(long mathGearId, String mathGear) {
		super();
		this.mathGearId = mathGearId;
		this.mathGear = mathGear;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "math_gear_id", unique = true, nullable = false)
	public long getMathGearId() {
		return this.mathGearId;
	}

	public void setMathGearId(long mathGearId) {
		this.mathGearId = mathGearId;
	}

	@Column(name = "math_gear", nullable = false, length = 10)
	public String getMathGear() {
		return mathGear;
	}

	public void setMathGear(String mathGear) {
		this.mathGear = mathGear;
	}

}
