package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "notification_status")
public class NotificationStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private long notificationStatusId;
	@JsonManagedReference
	private Announcements announcements;
	@JsonManagedReference
	private UserRegistration userRegistration;
	private String status;
	private Date readTimeStamp;

	public NotificationStatus() {
		super();
	}

	public NotificationStatus(long notificationStatusId,
			Announcements announcements, UserRegistration userRegistration,
			String status, Date readTimeStamp) {
		super();
		this.notificationStatusId = notificationStatusId;
		this.announcements = announcements;
		this.userRegistration = userRegistration;
		this.status = status;
		this.readTimeStamp = readTimeStamp;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "notification_status_id", unique = true, nullable = false)
	public long getNotificationStatusId() {
		return notificationStatusId;
	}


	public void setNotificationStatusId(long notificationStatusId) {
		this.notificationStatusId = notificationStatusId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "announcement_id", nullable = false)
	public Announcements getAnnouncements() {
		return announcements;
	}

	public void setAnnouncements(Announcements announcements) {
		this.announcements = announcements;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "reg_id", nullable = false)
	public UserRegistration getUserRegistration() {
		return userRegistration;
	}

	public void setUserRegistration(UserRegistration userRegistration) {
		this.userRegistration = userRegistration;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "read_time_stamp")	
	public Date getReadTimeStamp() {
		return readTimeStamp;
	}


	public void setReadTimeStamp(Date readTimeStamp) {
		this.readTimeStamp = readTimeStamp;
	}
}
