package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AcademicGrades generated by hbm2java
 */
@Entity
@Table(name = "parent_lastseen")
public class ParentLastseen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long parentLastseenId;
	@JsonManagedReference
	private UserRegistration parentId;
	private Date lastLoggedIn;
	private Date lastLoggedOut;
	private String lastSeenFeature;
	@Transient
	private String childName;
	@Transient
	private String parentEmail;

	public ParentLastseen() {
	}

	public ParentLastseen(long parentLastseenId,
			UserRegistration parentId) {
		this.parentLastseenId = parentLastseenId;
		this.parentId = parentId;
	}	
	
	public ParentLastseen(long parentLastseenId,
			UserRegistration parentId,Date lastLoggedIn,
			Date lastLoggedOut,String lastSeenFeature) {
		this.parentLastseenId = parentLastseenId;
		this.parentId = parentId;
		this.lastLoggedIn = lastLoggedIn;
		this.lastLoggedOut = lastLoggedOut;
		this.lastSeenFeature = lastSeenFeature;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "parent_lastseen_id", unique = true, nullable = false)
	public long getParentLastseenId() {
		return parentLastseenId;
	}

	public void setParentLastseenId(long parentLastseenId) {
		this.parentLastseenId = parentLastseenId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "parent_id", nullable = false)
	public UserRegistration getParentId() {
		return parentId;
	}

	public void setParentId(UserRegistration parentId) {
		this.parentId = parentId;
	}

	@Column(name = "last_logged_in")
	public Date getLastLoggedIn() {
		return lastLoggedIn;
	}

	public void setLastLoggedIn(Date lastLoggedIn) {
		this.lastLoggedIn = lastLoggedIn;
	}

	@Column(name = "last_logged_out")
	public Date getLastLoggedOut() {
		return lastLoggedOut;
	}

	public void setLastLoggedOut(Date lastLoggedOut) {
		this.lastLoggedOut = lastLoggedOut;
	}

	@Column(name = "last_seen_feature")
	public String getLastSeenFeature() {
		return lastSeenFeature;
	}

	public void setLastSeenFeature(String lastSeenFeature) {
		this.lastSeenFeature = lastSeenFeature;
	}
	
	@Transient
	public String getChildName() {
		return childName;
	}

	public void setChildName(String childName) {
		this.childName = childName;
	}

	@Transient
	public String getParentEmail() {
		return parentEmail;
	}

	public void setParentEmail(String parentEmail) {
		this.parentEmail = parentEmail;
	}
}
