package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * PerformancetaskGroups generated by hbm2java
 */
@Entity
@Table(name = "performancetask_groups")
public class PerformancetaskGroups implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long performanceGroupId;
	@JsonManagedReference
	private ClassStatus classStatus;
	private String groupName;
	private Integer maxNoOfStudents;
	private Integer minNoOfStudents;
	public PerformancetaskGroups() {
	}

	public PerformancetaskGroups(long performanceGroupId) {
		this.performanceGroupId = performanceGroupId;
	}

	public PerformancetaskGroups(long performanceGroupId,
			ClassStatus classStatus, String groupName, Integer maxNoOfStudents,
			Integer minNoOfStudents) {
		this.performanceGroupId = performanceGroupId;
		this.classStatus = classStatus;
		this.groupName = groupName;
		this.maxNoOfStudents = maxNoOfStudents;
		this.minNoOfStudents = minNoOfStudents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "performance_group_id", unique = true, nullable = false)
	public long getPerformanceGroupId() {
		return this.performanceGroupId;
	}

	public void setPerformanceGroupId(long performanceGroupId) {
		this.performanceGroupId = performanceGroupId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cs_id")
	public ClassStatus getClassStatus() {
		return this.classStatus;
	}

	public void setClassStatus(ClassStatus classStatus) {
		this.classStatus = classStatus;
	}

	@Column(name = "group_name", length = 20)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "MaxNo_of_students")
	public Integer getMaxNoOfStudents() {
		return this.maxNoOfStudents;
	}

	public void setMaxNoOfStudents(Integer maxNoOfStudents) {
		this.maxNoOfStudents = maxNoOfStudents;
	}

	@Column(name = "MinNo_of_students")
	public Integer getMinNoOfStudents() {
		return this.minNoOfStudents;
	}

	public void setMinNoOfStudents(Integer minNoOfStudents) {
		this.minNoOfStudents = minNoOfStudents;
	}
}
