package com.lp.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

// Generated May 8, 2015 3:18:14 PM by Hibernate Tools 4.0.0

/**
 * PerformanceGroupStudents generated by hbm2java
 */
@Entity
@Table(name = "performance_group_students")
public class PerformanceGroupStudents implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long performanceGroupStudentsId;
	@JsonManagedReference
	private Student student;
	@JsonManagedReference
	private PerformancetaskGroups performancetaskGroups;
	private String status;

	public PerformanceGroupStudents() {
	}

	public PerformanceGroupStudents(Student student,
			PerformancetaskGroups performancetaskGroups) {
		this.student = student;
		this.performancetaskGroups = performancetaskGroups;
	}

	public PerformanceGroupStudents(Student student,
			PerformancetaskGroups performancetaskGroups, String status) {
		this.student = student;
		this.performancetaskGroups = performancetaskGroups;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "performance_group_students_id", unique = true, nullable = false)
	public Long getPerformanceGroupStudentsId() {
		return this.performanceGroupStudentsId;
	}

	public void setPerformanceGroupStudentsId(Long performanceGroupStudentsId) {
		this.performanceGroupStudentsId = performanceGroupStudentsId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "student_id", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "performance_group_id", nullable = false)
	public PerformancetaskGroups getPerformancetaskGroups() {
		return this.performancetaskGroups;
	}

	public void setPerformancetaskGroups(
			PerformancetaskGroups performancetaskGroups) {
		this.performancetaskGroups = performancetaskGroups;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
