package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Periods generated by hbm2java
 */
@Entity
@Table(name = "periods")
public class Periods implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long periodId;
	@JsonManagedReference
	private Grade grade;
	private String periodName;
	private String startTime;
	private String endTime;

	public Periods() {
	}

	public Periods(long periodId, String periodName, String startTime,
			String endTime) {
		this.periodId = periodId;
		this.periodName = periodName;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public Periods(long periodId, Grade grade, String periodName,
			String startTime, String endTime) {
		this.periodId = periodId;
		this.grade = grade;
		this.periodName = periodName;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "period_id", unique = true, nullable = false)
	public long getPeriodId() {
		return this.periodId;
	}

	public void setPeriodId(long periodId) {
		this.periodId = periodId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "grade_id")
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@Column(name = "period_name", nullable = false, length = 20)
	public String getPeriodName() {
		return this.periodName;
	}

	public void setPeriodName(String periodName) {
		this.periodName = periodName;
	}

	@Column(name = "start_time", nullable = false, length = 8)
	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@Column(name = "end_time", nullable = false, length = 8)
	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}
}
