package com.lp.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.web.multipart.MultipartFile;

import com.fasterxml.jackson.annotation.JsonManagedReference;

// Generated May 18, 2015 12:16:07 PM by Hibernate Tools 4.0.0

/**
 * PtaskFiles generated by hbm2java
 */
@Entity
@Table(name = "ptask_files")
public class PtaskFiles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long fileId;
	@JsonManagedReference
	private Questions questions;
	private String filename;
	private long createdBy;
	@Transient
    private MultipartFile pfile;
    
	

	public PtaskFiles() {
	}

	public PtaskFiles(Questions questions, String filename, long createdBy) {
		this.questions = questions;
		this.filename = filename;
		this.createdBy = createdBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "file_id", unique = true, nullable = false)
	public Long getFileId() {
		return this.fileId;
	}

	public void setFileId(Long fileId) {
		this.fileId = fileId;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade=CascadeType.ALL)
	@JoinColumn(name = "performance_task_id", nullable = false)
	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	@Column(name = "filename", nullable = false)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}
	@Transient
	public MultipartFile getPfile() {
		return pfile;
	}

	public void setPfile(MultipartFile pfile) {
		this.pfile = pfile;
	}

}
