package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * QualityOfResponse generated by hbm2java
 */
@Entity
@Table(name = "quality_of_response")
public class QualityOfResponse implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer qorId;
	@NotNull
	@Size(min = 1, max = 100)
	private String response;

	public QualityOfResponse() {
	}

	public QualityOfResponse(String response) {
		this.response = response;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "qor_id", unique = true, nullable = false)
	public Integer getQorId() {
		return this.qorId;
	}

	public void setQorId(Integer qorId) {
		this.qorId = qorId;
	}

	@Column(name = "response", length = 100)
	public String getResponse() {
		return this.response;
	}

	public void setResponse(String response) {
		this.response = response;
	}
}
