package com.lp.model;

// default package
// Generated Jun 11, 2014 7:25:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Table;

import org.springframework.web.multipart.MultipartFile;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Unit generated by hbm2java
 */
public class QuestionsList implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5940790768471811123L;
	/**
	 * 
	 */
	private List<Questions> questions = new ArrayList<>();
	private List<JacTemplate> jacTemplate = new ArrayList<>();
	private List<SubQuestions> subQuestions = new ArrayList<>();
	@JsonIgnore
	private List<MultipartFile> files = new ArrayList<>();
	
	public List<Questions> getQuestions() {
		return questions;
	}	
	public void setQuestions(List<Questions> questions) {
		this.questions = questions;
	}
	public List<JacTemplate> getJacTemplate() {
		return jacTemplate;
	}
	public void setJacTemplate(List<JacTemplate> jacTemplate) {
		this.jacTemplate = jacTemplate;
	}
	public List<SubQuestions> getSubQuestions() {
		return subQuestions;
	}
	public void setSubQuestions(List<SubQuestions> subQuestions) {
		this.subQuestions = subQuestions;
	}
	
	public List<MultipartFile> getFiles() {
		return files;
	}
	public void setFiles(List<MultipartFile> files) {
		this.files = files;
	}
	
}
