package com.lp.model;

// default package
// Generated Jun 11, 2014 7:25:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Unit generated by hbm2java
 */
/*@Entity
@Table(name = "read_reg_questions")*/
public class QuizQuestionsList implements java.io.Serializable {

	private static final long serialVersionUID = 5940790768471811123L;
	@JsonIgnore
	private List<ReadRegQuestions> readRegQuestionsLt = new ArrayList<>();
	@JsonIgnore
	private List<ReadRegAnswers> readRegAnswersLt = new ArrayList<>();
	
	@Transient
	private long titleId;
	@Transient
	private int count;
	
	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	public long getTitleId() {
		return titleId;
	}

	public void setTitleId(long titleId) {
		this.titleId = titleId;
	}

	public QuizQuestionsList() {
	}	

	public QuizQuestionsList(List<ReadRegQuestions> readRegQuestionsLt, List<ReadRegAnswers> readRegAnswersLt,
			long titleId, int count) {
		super();
		this.readRegQuestionsLt = readRegQuestionsLt;
		this.readRegAnswersLt = readRegAnswersLt;
		this.titleId = titleId;
		this.count = count;
	}
	
	@JsonIgnore
	public List<ReadRegQuestions> getReadRegQuestionsLt() {
		return readRegQuestionsLt;
	}
	
	public void setReadRegQuestionsLt(List<ReadRegQuestions> readRegQuestionsLt) {
		this.readRegQuestionsLt = readRegQuestionsLt;
	}
	
	@JsonIgnore
	public List<ReadRegAnswers> getReadRegAnswersLt() {
		return readRegAnswersLt;
	}

	public void setReadRegAnswersLt(List<ReadRegAnswers> readRegAnswersLt) {
		this.readRegAnswersLt = readRegAnswersLt;
	}

}
