package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Interest generated by hbm2java
 */
@Entity
@Table(name = "reading_types")
public class ReadingTypes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long readingTypesId;
	private String readingTypes;

	
	public ReadingTypes() {
	}

	public ReadingTypes(long readingTypesId, String readingTypes) {
		this.readingTypesId = readingTypesId;
		this.readingTypes = readingTypes;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "reading_type_id", unique = true, nullable = false)	
	public long getReadingTypesId() {
		return readingTypesId;
	}

	public void setReadingTypesId(long readingTypesId) {
		this.readingTypesId = readingTypesId;
	}
	@Column(name = "reading_type", unique = true, nullable = false, length = 30)
	public String getReadingTypes() {
		return readingTypes;
	}

	public void setReadingTypes(String readingTypes) {
		this.readingTypes = readingTypes;
	}

}
