package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegisterForClassId generated by hbm2java
 */
@Embeddable
public class RegisterForClassId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long gradeClassId;
	private long studentId;

	public RegisterForClassId() {
	}

	public RegisterForClassId(long gradeClassId, long studentId) {
		this.gradeClassId = gradeClassId;
		this.studentId = studentId;
	}

	@Column(name = "grade_class_id", nullable = false)
	public long getGradeClassId() {
		return this.gradeClassId;
	}

	public void setGradeClassId(long gradeClassId) {
		this.gradeClassId = gradeClassId;
	}

	@Column(name = "student_id", nullable = false)
	public long getStudentId() {
		return this.studentId;
	}

	public void setStudentId(long studentId) {
		this.studentId = studentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegisterForClassId))
			return false;
		RegisterForClassId castOther = (RegisterForClassId) other;

		return (this.getGradeClassId() == castOther.getGradeClassId())
				&& (this.getStudentId() == castOther.getStudentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getGradeClassId();
		result = 37 * result + (int) this.getStudentId();
		return result;
	}

}
