package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "report")
public class Report implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long reportId;
	@JsonManagedReference
	private Citizenship citizenship;
	@JsonManagedReference
	private Student student;
	@JsonManagedReference
	private Comments comments;
	@JsonManagedReference
	private ClassStatus classStatus;
	@JsonManagedReference
	private AcademicGrades academicGrades;
	private float homeworkPerc;
	private float assignmentPerc;
	private int presentdays;
	private int absentdays;
	private int excusedabsentdays;
	private int tardydays;
	private int excusedtardydays;
	private Date releaseDate;
	private String parentComments;
	private Date parentCommentsDate;
	private float performancePerc;

	public Report() {
	}

	public Report(Citizenship citizenship, Student student, Comments comments,
			AcademicGrades academicGrades, float homeworkPerc,
			float assignmentPerc, int presentdays, int absentdays,
			int excusedabsentdays, int tardydays, int excusedtardydays, float performancePerc) {
		this.citizenship = citizenship;
		this.student = student;
		this.comments = comments;
		this.academicGrades = academicGrades;
		this.homeworkPerc = homeworkPerc;
		this.assignmentPerc = assignmentPerc;
		this.presentdays = presentdays;
		this.absentdays = absentdays;
		this.excusedabsentdays = excusedabsentdays;
		this.tardydays = tardydays;
		this.excusedtardydays = excusedtardydays;
		this.performancePerc = performancePerc;
	}

	public Report(Citizenship citizenship, Student student, Comments comments,
			ClassStatus classStatus, AcademicGrades academicGrades,
			float homeworkPerc, float assignmentPerc, int presentdays,
			int absentdays, int excusedabsentdays, int tardydays,
			int excusedtardydays, Date releaseDate, String parentComments,
			Date parentCommentsDate, float performancePerc) {
		this.citizenship = citizenship;
		this.student = student;
		this.comments = comments;
		this.classStatus = classStatus;
		this.academicGrades = academicGrades;
		this.homeworkPerc = homeworkPerc;
		this.assignmentPerc = assignmentPerc;
		this.presentdays = presentdays;
		this.absentdays = absentdays;
		this.excusedabsentdays = excusedabsentdays;
		this.tardydays = tardydays;
		this.excusedtardydays = excusedtardydays;
		this.releaseDate = releaseDate;
		this.parentComments = parentComments;
		this.parentCommentsDate = parentCommentsDate;
		this.performancePerc = performancePerc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "report_id", unique = true, nullable = false)
	public Long getReportId() {
		return this.reportId;
	}

	public void setReportId(Long reportId) {
		this.reportId = reportId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "Citizenship_id", nullable = false)
	public Citizenship getCitizenship() {
		return this.citizenship;
	}

	public void setCitizenship(Citizenship citizenship) {
		this.citizenship = citizenship;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "student_id", nullable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "comment_id", nullable = false)
	public Comments getComments() {
		return this.comments;
	}

	public void setComments(Comments comments) {
		this.comments = comments;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cs_id")
	public ClassStatus getClassStatus() {
		return this.classStatus;
	}

	public void setClassStatus(ClassStatus classStatus) {
		this.classStatus = classStatus;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "acedamic_grade_id", nullable = false)
	public AcademicGrades getAcademicGrades() {
		return this.academicGrades;
	}

	public void setAcademicGrades(AcademicGrades academicGrades) {
		this.academicGrades = academicGrades;
	}

	@Column(name = "homework_perc", nullable = false, precision = 12, scale = 0)
	public float getHomeworkPerc() {
		return this.homeworkPerc;
	}

	public void setHomeworkPerc(float homeworkPerc) {
		this.homeworkPerc = homeworkPerc;
	}

	@Column(name = "assignment_perc", nullable = false, precision = 12, scale = 0)
	public float getAssignmentPerc() {
		return this.assignmentPerc;
	}

	public void setAssignmentPerc(float assignmentPerc) {
		this.assignmentPerc = assignmentPerc;
	}

	@Column(name = "presentdays", nullable = false)
	public int getPresentdays() {
		return this.presentdays;
	}

	public void setPresentdays(int presentdays) {
		this.presentdays = presentdays;
	}

	@Column(name = "absentdays", nullable = false)
	public int getAbsentdays() {
		return this.absentdays;
	}

	public void setAbsentdays(int absentdays) {
		this.absentdays = absentdays;
	}

	@Column(name = "excusedabsentdays", nullable = false)
	public int getExcusedabsentdays() {
		return this.excusedabsentdays;
	}

	public void setExcusedabsentdays(int excusedabsentdays) {
		this.excusedabsentdays = excusedabsentdays;
	}

	@Column(name = "tardydays", nullable = false)
	public int getTardydays() {
		return this.tardydays;
	}

	public void setTardydays(int tardydays) {
		this.tardydays = tardydays;
	}

	@Column(name = "excusedtardydays", nullable = false)
	public int getExcusedtardydays() {
		return this.excusedtardydays;
	}

	public void setExcusedtardydays(int excusedtardydays) {
		this.excusedtardydays = excusedtardydays;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "release_date", length = 10)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "parent_comments", length = 200)
	public String getParentComments() {
		return this.parentComments;
	}

	public void setParentComments(String parentComments) {
		this.parentComments = parentComments;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "parent_comments_date", length = 10)
	public Date getParentCommentsDate() {
		return this.parentCommentsDate;
	}

	public void setParentCommentsDate(Date parentCommentsDate) {
		this.parentCommentsDate = parentCommentsDate;
	}

	@Column(name = "performance_perc", nullable = false, precision = 12, scale = 0)
	public float getPerformancePerc() {
		return performancePerc;
	}

	public void setPerformancePerc(float performancePerc) {
		this.performancePerc = performancePerc;
	}

}
