package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * RtiGroups generated by hbm2java
 */
@Entity
@Table(name = "rti_groups")
public class RtiGroups implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long rtiGroupId;
	@NotNull
	@Size(min = 1, max = 30)
	private String rtiGroupName;

	public RtiGroups() {
	}

	public RtiGroups(long rtiGroupId, String rtiGroupName) {
		this.rtiGroupId = rtiGroupId;
		this.rtiGroupName = rtiGroupName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rti_group_id", unique = true, nullable = false)
	public long getRtiGroupId() {
		return this.rtiGroupId;
	}

	public void setRtiGroupId(long rtiGroupId) {
		this.rtiGroupId = rtiGroupId;
	}

	@Column(name = "rti_group_name", nullable = false, length = 30)
	public String getRtiGroupName() {
		return this.rtiGroupName;
	}

	public void setRtiGroupName(String rtiGroupName) {
		this.rtiGroupName = rtiGroupName;
	}
}
