package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RubricScalings generated by hbm2java
 */
@Entity
@Table(name = "rubric_scalings")
public class RubricScalings implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long rubricScalingId;
	private int rubricScaling;

	public RubricScalings() {
	}

	public RubricScalings(long rubricScalingId, int rubricScaling) {
		this.rubricScalingId = rubricScalingId;
		this.rubricScaling = rubricScaling;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rubric_scaling_id", unique = true, nullable = false)
	public long getRubricScalingId() {
		return this.rubricScalingId;
	}

	public void setRubricScalingId(long rubricScalingId) {
		this.rubricScalingId = rubricScalingId;
	}

	@Column(name = "rubric_scaling", nullable = false)
	public int getRubricScaling() {
		return this.rubricScaling;
	}

	public void setRubricScaling(int rubricScaling) {
		this.rubricScaling = rubricScaling;
	}
}
