package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Rubric generated by hbm2java
 */
@Entity
@Table(name = "rubric")
public class Rubric implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long rubricId;
	@JsonManagedReference
	private RubricTypes rubricTypes;
	@JsonIgnore
	private Questions questions;
	@JsonManagedReference
	private RubricScalings rubricScalings;
	private String dimension1;
	private String dimension2;
	private String dimension3;
	private String dimension4;
	private String score;
	private Integer dimension1Total;
	private Integer dimension2Total;
	private Integer dimension3Total;
	private Integer dimension4Total;
	private Long createdBy;
	public Rubric() {
	}

	public Rubric(long rubricId) {
		this.rubricId = rubricId;
	}

	public Rubric(long rubricId, RubricTypes rubricTypes, Questions questions,
			RubricScalings rubricScalings, String dimension1,
			String dimension2, String dimension3, String dimension4, String score,
			Integer dimension1Total, Integer dimension2Total,
			Integer dimension3Total, Integer dimension4Total, Long createdBy) {
		this.rubricId = rubricId;
		this.rubricTypes = rubricTypes;
		this.questions = questions;
		this.rubricScalings = rubricScalings;
		this.dimension1 = dimension1;
		this.dimension2 = dimension2;
		this.dimension3 = dimension3;
		this.dimension4 = dimension4;
		this.score = score;
		this.dimension1Total = dimension1Total;
		this.dimension2Total = dimension2Total;
		this.dimension3Total = dimension3Total;
		this.dimension4Total = dimension4Total;
		this.createdBy = createdBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rubric_id", unique = true, nullable = false)
	public long getRubricId() {
		return this.rubricId;
	}

	public void setRubricId(long rubricId) {
		this.rubricId = rubricId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "rubric_type_id")
	public RubricTypes getRubricTypes() {
		return this.rubricTypes;
	}

	public void setRubricTypes(RubricTypes rubricTypes) {
		this.rubricTypes = rubricTypes;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "perf_task_quest_id")
	public Questions getQuestions() {
		return this.questions;
	}

	public void setQuestions(Questions questions) {
		this.questions = questions;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "rubric_scaling_id")
	public RubricScalings getRubricScalings() {
		return this.rubricScalings;
	}

	public void setRubricScalings(RubricScalings rubricScalings) {
		this.rubricScalings = rubricScalings;
	}

	@Column(name = "dimension1", length = 1000)
	public String getDimension1() {
		return this.dimension1;
	}

	public void setDimension1(String dimension1) {
		this.dimension1 = dimension1;
	}

	@Column(name = "dimension2", length = 1000)
	public String getDimension2() {
		return this.dimension2;
	}

	public void setDimension2(String dimension2) {
		this.dimension2 = dimension2;
	}

	@Column(name = "dimension3", length = 1000)
	public String getDimension3() {
		return this.dimension3;
	}

	public void setDimension3(String dimension3) {
		this.dimension3 = dimension3;
	}

	@Column(name = "dimension4", length = 1000)
	public String getDimension4() {
		return this.dimension4;
	}

	public void setDimension4(String dimension4) {
		this.dimension4 = dimension4;
	}

	@Column(name = "dimension1_total")
	public Integer getDimension1Total() {
		return this.dimension1Total;
	}

	public void setDimension1Total(Integer dimension1Total) {
		this.dimension1Total = dimension1Total;
	}

	@Column(name = "dimension2_total")
	public Integer getDimension2Total() {
		return this.dimension2Total;
	}

	public void setDimension2Total(Integer dimension2Total) {
		this.dimension2Total = dimension2Total;
	}

	@Column(name = "dimension3_total")
	public Integer getDimension3Total() {
		return this.dimension3Total;
	}

	public void setDimension3Total(Integer dimension3Total) {
		this.dimension3Total = dimension3Total;
	}

	@Column(name = "dimension4_total")
	public Integer getDimension4Total() {
		return this.dimension4Total;
	}

	public void setDimension4Total(Integer dimension4Total) {
		this.dimension4Total = dimension4Total;
	}

	@Column(name = "created_by")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}
	
	@Column(name = "score")
	public String getScore() {
		return score;
	}

	public void setScore(String score) {
		this.score = score;
	}
}
