package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RubricScore generated by hbm2java
 */
@Entity
@Table(name = "rubric_score")
public class RubricScore implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long rubricScoreId;
	private Integer rubricScore;
	public RubricScore() {
	}

	public RubricScore(long rubricScoreId) {
		this.rubricScoreId = rubricScoreId;
	}

	public RubricScore(long rubricScoreId, Integer rubricScore) {
		this.rubricScoreId = rubricScoreId;
		this.rubricScore = rubricScore;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rubric_score_id", unique = true, nullable = false)
	public long getRubricScoreId() {
		return this.rubricScoreId;
	}

	public void setRubricScoreId(long rubricScoreId) {
		this.rubricScoreId = rubricScoreId;
	}

	@Column(name = "rubric_score")
	public Integer getRubricScore() {
		return this.rubricScore;
	}

	public void setRubricScore(Integer rubricScore) {
		this.rubricScore = rubricScore;
	}
}
