package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * SchoolSchedule generated by hbm2java
 */
@Entity
@Table(name = "school_schedule")
public class SchoolSchedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long schoolScheduleId;
	@JsonManagedReference
	private School school;
	private int noOfDays;
	private int noOfClassPeriods;
	private int periodRange;
	private int passingTime;
	private int homeRoomTime;
	private String schoolStartTime;
	private String schoolEndTime;
	private int noOfTeachers;
	private int noOfSections;
	private Date startDate;
	private Date endDate;
	@Transient
	private Long dayStartTime;
	@Transient
	private Long dayStartTimeMin;
	@Transient
	private String dayStartTimeMeridian;
	
	@Transient
	private Long dayEndTime;
	@Transient
	private Long dayEndTimeMin;
	@Transient
	private String dayEndTimeMeridian;

	public SchoolSchedule() {
	}

	public SchoolSchedule(long schoolScheduleId, School school, int noOfDays,
			int noOfClassPeriods, int periodRange, int passingTime,
			int homeRoomTime, String schoolStartTime, String schoolEndTime,
			int noOfTeachers, int noOfSections, Date startDate, Date endDate) {
		this.schoolScheduleId = schoolScheduleId;
		this.school = school;
		this.noOfDays = noOfDays;
		this.noOfClassPeriods = noOfClassPeriods;
		this.periodRange = periodRange;
		this.passingTime = passingTime;
		this.homeRoomTime = homeRoomTime;
		this.schoolStartTime = schoolStartTime;
		this.schoolEndTime = schoolEndTime;
		this.noOfTeachers = noOfTeachers;
		this.noOfSections = noOfSections;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "school_schedule_id", unique = true, nullable = false)
	public long getSchoolScheduleId() {
		return this.schoolScheduleId;
	}

	public void setSchoolScheduleId(long schoolScheduleId) {
		this.schoolScheduleId = schoolScheduleId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "school_id", nullable = false)
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "no_of_days", nullable = false)
	public int getNoOfDays() {
		return this.noOfDays;
	}

	public void setNoOfDays(int noOfDays) {
		this.noOfDays = noOfDays;
	}

	@Column(name = "no_of_class_periods", nullable = false)
	public int getNoOfClassPeriods() {
		return this.noOfClassPeriods;
	}

	public void setNoOfClassPeriods(int noOfClassPeriods) {
		this.noOfClassPeriods = noOfClassPeriods;
	}

	@Column(name = "period_range", nullable = false)
	public int getPeriodRange() {
		return this.periodRange;
	}

	public void setPeriodRange(int periodRange) {
		this.periodRange = periodRange;
	}

	@Column(name = "passing_time", nullable = false)
	public int getPassingTime() {
		return this.passingTime;
	}

	public void setPassingTime(int passingTime) {
		this.passingTime = passingTime;
	}

	@Column(name = "home_room_time", nullable = false)
	public int getHomeRoomTime() {
		return this.homeRoomTime;
	}

	public void setHomeRoomTime(int homeRoomTime) {
		this.homeRoomTime = homeRoomTime;
	}

	//@Temporal(TemporalType.TIME)
	@Column(name = "school_start_time", nullable = false, length = 8)
	public String getSchoolStartTime() {
		return this.schoolStartTime;
	}

	public void setSchoolStartTime(String schoolStartTime) {
		this.schoolStartTime = schoolStartTime;
	}

	
	@Column(name = "school_end_time", nullable = false, length = 8)
	public String getSchoolEndTime() {
		return this.schoolEndTime;
	}

	public void setSchoolEndTime(String schoolEndTime) {
		this.schoolEndTime = schoolEndTime;
	}

	@Column(name = "no_of_teachers", nullable = false)
	public int getNoOfTeachers() {
		return this.noOfTeachers;
	}

	public void setNoOfTeachers(int noOfTeachers) {
		this.noOfTeachers = noOfTeachers;
	}

	@Column(name = "no_of_sections", nullable = false)
	public int getNoOfSections() {
		return this.noOfSections;
	}

	public void setNoOfSections(int noOfSections) {
		this.noOfSections = noOfSections;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	
	@Transient
	public Long getDayStartTime() {
		return dayStartTime;
	}

	public void setDayStartTime(Long dayStartTime) {
		this.dayStartTime = dayStartTime;
	}
	@Transient
	public Long getDayStartTimeMin() {
		return dayStartTimeMin;
	}

	public void setDayStartTimeMin(Long dayStartTimeMin) {
		this.dayStartTimeMin = dayStartTimeMin;
	}
	@Transient
	public String getDayStartTimeMeridian() {
		return dayStartTimeMeridian;
	}

	public void setDayStartTimeMeridian(String dayStartTimeMeridian) {
		this.dayStartTimeMeridian = dayStartTimeMeridian;
	}
	@Transient
	public Long getDayEndTime() {
		return dayEndTime;
	}

	public void setDayEndTime(Long dayEndTime) {
		this.dayEndTime = dayEndTime;
	}
	@Transient
	public Long getDayEndTimeMin() {
		return dayEndTimeMin;
	}

	public void setDayEndTimeMin(Long dayEndTimeMin) {
		this.dayEndTimeMin = dayEndTimeMin;
	}
	@Transient
	public String getDayEndTimeMeridian() {
		return dayEndTimeMeridian;
	}

	public void setDayEndTimeMeridian(String dayEndTimeMeridian) {
		this.dayEndTimeMeridian = dayEndTimeMeridian;
	}

}
