package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * SchoolDays generated by hbm2java
 */
@Entity
@Table(name = "school_days")
public class SchoolDays implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long schoolDaysId;
	@JsonManagedReference
	private School school;
	@JsonManagedReference
	private Days days;
	private Date createDate;
	private Date changeDate;
	private String status;

	public SchoolDays() {
	}

	public SchoolDays(long schoolDaysId, Date changeDate) {
		this.schoolDaysId = schoolDaysId;
		this.changeDate = changeDate;
	}

	public SchoolDays(long schoolDaysId, School school, Days days,
			Date createDate, Date changeDate, String status) {
		this.schoolDaysId = schoolDaysId;
		this.school = school;
		this.days = days;
		this.createDate = createDate;
		this.changeDate = changeDate;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "school_days_id", unique = true, nullable = false)
	public long getSchoolDaysId() {
		return this.schoolDaysId;
	}

	public void setSchoolDaysId(long schoolDaysId) {
		this.schoolDaysId = schoolDaysId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "school_id")
	public School getSchool() {
		return this.school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "day_id")
	public Days getDays() {
		return this.days;
	}

	public void setDays(Days days) {
		this.days = days;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_date", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
