package com.lp.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * SchoolLevel generated by hbm2java
 */

@Entity
@Table(name = "school_level")
public class SchoolLevel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long schoolLevelId;
	@NotNull
	@Size(min = 1, max = 50)
	private String schoolLevelName;

	public SchoolLevel() {
	}

	public SchoolLevel(long schoolLevelId, String schoolLevelName) {
		this.schoolLevelId = schoolLevelId;
		this.schoolLevelName = schoolLevelName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "school_level_id", unique = true, nullable = false)
	public long getSchoolLevelId() {
		return this.schoolLevelId;
	}

	public void setSchoolLevelId(long schoolLevelId) {
		this.schoolLevelId = schoolLevelId;
	}

	@Column(name = "school_level_name", nullable = false, length = 45)
	public String getSchoolLevelName() {
		return this.schoolLevelName;
	}

	public void setSchoolLevelName(String schoolLevelName) {
		this.schoolLevelName = schoolLevelName;
	}
}
