package com.lp.model;

// default package
// Generated Aug 26, 2014 3:48:18 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * School generated by hbm2java
 */
@Entity
@Table(name = "school", uniqueConstraints = {@UniqueConstraint(columnNames="school_abbr"), @UniqueConstraint(columnNames = {
		"school_name", "school_type_id", "school_level_id", "city", "state_id"})})
public class School implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private long schoolId;
	@JsonManagedReference
	private States states;
	@JsonManagedReference
	private SchoolType schoolType;
	@JsonManagedReference
	private SchoolLevel schoolLevel;
	@JsonManagedReference
	private District district;
	@JsonManagedReference
	private AcademicYear academicYear;
	
	private String schoolName;
	private int noOfStudents;
	private String city;
	private String phoneNumber;
	private String faxNumber;
	private Date createDate;
	private Date changeDate;
	private Date registrationDate;
	private String logoLink;
	private int classStrength;
	private String leveling;
	private String genderEquity;
	@Transient
	private String schoolTypeId;
	@Transient
	private String schoolLevelId;
	@Transient
	private String countryId;
	@Transient
	private String stateId;
	private String schoolAbbr;
	private Date promotStartDate;
	private Date promotEndDate;
	@Transient
	private String districtId;

	
	public School() {
	}

	public School(long schoolId, States states, SchoolType schoolType,
			SchoolLevel schoolLevel, String schoolName, int noOfStudents,
			String city, Date createDate, Date changeDate,
			Date registrationDate, int classStrength, String leveling,
			String genderEquity,Date promotStartDate,Date promotEndDate) {
		this.states = states;
		this.schoolType = schoolType;
		this.schoolLevel = schoolLevel;
		this.schoolName = schoolName;
		this.noOfStudents = noOfStudents;
		this.city = city;
		this.createDate = createDate;
		this.changeDate = changeDate;
		this.registrationDate = registrationDate;
		this.schoolId = schoolId;
		this.classStrength = classStrength;
		this.leveling = leveling;
		this.genderEquity = genderEquity;
		this.promotStartDate=promotStartDate;
		this.promotEndDate=promotEndDate;

	}

	public School(States states, SchoolType schoolType,
			SchoolLevel schoolLevel, String schoolName, int noOfStudents,
			String city, String phoneNumber, String faxNumber, Date createDate,
			Date changeDate, Date registrationDate, String logoLink,
			int classStrength, String leveling, String genderEquity,Date promotStartDate,Date promotEndDate,
			District district, AcademicYear academicYear) {
		this.states = states;
		this.schoolType = schoolType;
		this.schoolLevel = schoolLevel;
		this.schoolName = schoolName;
		this.noOfStudents = noOfStudents;
		this.city = city;
		this.phoneNumber = phoneNumber;
		this.faxNumber = faxNumber;
		this.createDate = createDate;
		this.changeDate = changeDate;
		this.registrationDate = registrationDate;
		this.logoLink = logoLink;
		this.classStrength = classStrength;
		this.leveling = leveling;
		this.genderEquity = genderEquity;
		this.promotStartDate=promotStartDate;
		this.promotEndDate=promotEndDate;
		this.district=district;
		this.academicYear = academicYear;
	}

	@Transient
	public String getSchoolTypeId() {
		return schoolTypeId;
	}

	public void setSchoolTypeId(String schoolTypeId) {
		this.schoolTypeId = schoolTypeId;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "district_id")
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "academic_year_id")
	public AcademicYear getAcademicYear() {
		return academicYear;
	}

	public void setAcademicYear(AcademicYear academicYear) {
		this.academicYear = academicYear;
	}

	@Transient
	public String getSchoolLevelId() {
		return schoolLevelId;
	}

	public void setSchoolLevelId(String schoolLevelId) {
		this.schoolLevelId = schoolLevelId;
	}
	@Transient
	public String getdistrictId() {
		return districtId;
	}

	public void sedistrictId(String districtId) {
		this.districtId = districtId;
	}
	@Transient
	public String getCountryId() {
		return countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	@Transient
	public String getStateId() {
		return stateId;
	}

	public void setStateId(String stateId) {
		this.stateId = stateId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "school_id", unique = true, nullable = false)
	public long getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(long schoolId) {
		this.schoolId = schoolId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "state_id", nullable = false)
	public States getStates() {
		return this.states;
	}

	public void setStates(States states) {
		this.states = states;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "school_type_id", nullable = false)
	public SchoolType getSchoolType() {
		return this.schoolType;
	}

	public void setSchoolType(SchoolType schoolType) {
		this.schoolType = schoolType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "school_level_id", nullable = false)
	public SchoolLevel getSchoolLevel() {
		return this.schoolLevel;
	}

	public void setSchoolLevel(SchoolLevel schoolLevel) {
		this.schoolLevel = schoolLevel;
	}

	@Column(name = "school_name", nullable = false, length = 45)
	public String getSchoolName() {
		return this.schoolName;
	}

	public void setSchoolName(String schoolName) {
		this.schoolName = schoolName;
	}

	@Column(name = "no_of_students", nullable = false)
	public int getNoOfStudents() {
		return this.noOfStudents;
	}

	public void setNoOfStudents(int noOfStudents) {
		this.noOfStudents = noOfStudents;
	}

	@Column(name = "city", nullable = false, length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "phone_number", length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "fax_number", length = 45)
	public String getFaxNumber() {
		return this.faxNumber;
	}

	public void setFaxNumber(String faxNumber) {
		this.faxNumber = faxNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_date", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}
     
	@Temporal(TemporalType.DATE)
	@Column(name = "registration_date", nullable = false, length = 10)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "logo_link", length = 50)
	public String getLogoLink() {
		return this.logoLink;
	}

	public void setLogoLink(String logoLink) {
		this.logoLink = logoLink;
	}

	@Column(name = "class_strength")
	public int getClassStrength() {
		return this.classStrength;
	}

	public void setClassStrength(int classStrength) {
		this.classStrength = classStrength;
	}

	@Column(name = "leveling", length = 10)
	public String getLeveling() {
		return this.leveling;
	}

	public void setLeveling(String leveling) {
		this.leveling = leveling;
	}

	@Column(name = "gender_equity", length = 10)
	public String getGenderEquity() {
		return this.genderEquity;
	}

	public void setGenderEquity(String genderEquity) {
		this.genderEquity = genderEquity;
	}
	
    @Column(name="school_abbr",unique=true,length=50)
	public String getSchoolAbbr() {
		return schoolAbbr;
	}

	public void setSchoolAbbr(String schoolAbbr) {
		this.schoolAbbr = schoolAbbr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "promot_startdate", length = 10)
	public Date getPromotStartDate() {
		return this.promotStartDate;
	}

	public void setPromotStartDate(Date promotStartDate) {
		this.promotStartDate = promotStartDate;
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "promot_enddate", length = 10)
	public Date getPromotEndDate() {
		return this.promotEndDate;
	}

	public void setPromotEndDate(Date promotenddate) {
		this.promotEndDate = promotenddate;
	}
}
