package com.lp.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * SchoolType generated by hbm2java
 */

@Entity
@Table(name = "school_type")
public class SchoolType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long schoolTypeId;
	@NotNull
	@Size(min = 1, max = 50)
	private String schoolTypeName;

	public SchoolType() {
	}

	public SchoolType(long schoolTypeId, String schoolTypeName) {
		this.schoolTypeId = schoolTypeId;
		this.schoolTypeName = schoolTypeName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "school_type_id", unique = true, nullable = false)
	public long getSchoolTypeId() {
		return this.schoolTypeId;
	}

	public void setSchoolTypeId(long schoolTypeId) {
		this.schoolTypeId = schoolTypeId;
	}

	@Column(name = "school_type_name", nullable = false, length = 45)
	public String getSchoolTypeName() {
		return this.schoolTypeName;
	}

	public void setSchoolTypeName(String schoolTypeName) {
		this.schoolTypeName = schoolTypeName;
	}
}
