package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Section generated by hbm2java
 */
@Entity
@Table(name = "section")
public class Section implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long sectionId;
	@JsonManagedReference
	private GradeClasses gradeClasses;
	@JsonManagedReference
	private GradeLevel gradeLevel;
	private String section;
	private String status;
	@Transient
	private long teacherId;
	@Transient
	private long homeroomId;
	

	public Section() {
	}

	public Section(long sectionId, String section, String status) {
		this.sectionId = sectionId;
		this.section = section;
		this.status = status;
	}

	public Section(long sectionId, GradeClasses gradeClasses,
			GradeLevel gradeLevel, String section, String status) {
		this.sectionId = sectionId;
		this.gradeClasses = gradeClasses;
		this.gradeLevel = gradeLevel;
		this.section = section;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "section_id", unique = true, nullable = false)
	public long getSectionId() {
		return this.sectionId;
	}

	public void setSectionId(long sectionId) {
		this.sectionId = sectionId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "grade_class_id")
	public GradeClasses getGradeClasses() {
		return this.gradeClasses;
	}

	public void setGradeClasses(GradeClasses gradeClasses) {
		this.gradeClasses = gradeClasses;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "grade_level_id")
	public GradeLevel getGradeLevel() {
		return this.gradeLevel;
	}

	public void setGradeLevel(GradeLevel gradeLevel) {
		this.gradeLevel = gradeLevel;
	}

	@Column(name = "section", nullable = false, length = 20)
	public String getSection() {
		return this.section;
	}

	public void setSection(String section) {
		this.section = section;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	@Transient
	public long getTeacherId() {
		return teacherId;
	}

	public void setTeacherId(long teacherId) {
		this.teacherId = teacherId;
	}
	
	@Transient
	public long getHomeroomId() {
		return homeroomId;
	}

	public void setHomeroomId(long homeroomId) {
		this.homeroomId = homeroomId;
	}
}
