package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.validator.constraints.NotEmpty;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Security generated by hbm2java
 */
@Entity
@Table(name = "security", uniqueConstraints = @UniqueConstraint(columnNames = "reg_id"))
public class Security implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long securityId;
	@JsonManagedReference
	private UserRegistration userRegistration;
	@JsonManagedReference
	private SecurityQuestion securityQuestion;
	private String answer;
	@NotNull
	@NotEmpty
	private String verificationCode;
	private String status;
	private Date createDate;
	private Date changeDate;
	@Transient
	private String emailId;
	@Transient
	private long securityQuestionId;
	

	public Security() {
	}

	public Security(long securityId, UserRegistration userRegistration,
			SecurityQuestion securityQuestion, String answer, Date createDate,
			Date changeDate) {
		this.securityId = securityId;
		this.userRegistration = userRegistration;
		this.securityQuestion = securityQuestion;
		this.answer = answer;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	public Security(long securityId, UserRegistration userRegistration,
			SecurityQuestion securityQuestion, String answer,
			String verificationCode, String status, Date createDate,
			Date changeDate) {
		this.securityId = securityId;
		this.userRegistration = userRegistration;
		this.securityQuestion = securityQuestion;
		this.answer = answer;
		this.verificationCode = verificationCode;
		this.status = status;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "security_id", unique = true, nullable = false)
	public long getSecurityId() {
		return this.securityId;
	}

	public void setSecurityId(long securityId) {
		this.securityId = securityId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "reg_id", unique = true, nullable = false)
	@NotFound(action=NotFoundAction.IGNORE)
	public UserRegistration getUserRegistration() {
		return this.userRegistration;
	}

	public void setUserRegistration(UserRegistration userRegistration) {
		this.userRegistration = userRegistration;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sec_question_id", nullable = false)
	public SecurityQuestion getSecurityQuestion() {
		return this.securityQuestion;
	}

	public void setSecurityQuestion(SecurityQuestion securityQuestion) {
		this.securityQuestion = securityQuestion;
	}

	@Column(name = "answer", nullable = false, length = 45)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "verification_code", length = 45)
	public String getVerificationCode() {
		return this.verificationCode;
	}

	public void setVerificationCode(String verificationCode) {
		this.verificationCode = verificationCode;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_date", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}
	@Transient
	public long getsecurityQuestionId() {
		return securityQuestionId;
	}

	public void setsecurityQuestionId(long securityQuestionId) {
		this.securityQuestionId = securityQuestionId;
	}
    @Transient
	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}


}
