package com.lp.model;

// default package
// Generated Jun 11, 2014 7:25:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Table;

import org.springframework.web.multipart.MultipartFile;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Unit generated by hbm2java
 */
public class StemUnitActList implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5940790768471811123L;
	/**
	 * 
	 */
	private List<StemUnitActivity> stemUnitAct = new ArrayList<>();
	@JsonIgnore
	private List<MultipartFile> files = new ArrayList<>();
	
	private List<Legend> legendList = new ArrayList<Legend>();
	
	
	public List<MultipartFile> getFiles() {
		return files;
	}
	public void setFiles(List<MultipartFile> files) {
		this.files = files;
	}
	public List<Legend> getLegendList() {
		return legendList;
	}
	public void setLegendList(List<Legend> legendList) {
		this.legendList = legendList;
	}
	public List<StemUnitActivity> getStemUnitAct() {
		return stemUnitAct;
	}
	public void setStemUnitAct(List<StemUnitActivity> stemUnitAct) {
		this.stemUnitAct = stemUnitAct;
	}	
}
