package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * StudentAssignmentStatus generated by hbm2java
 */
@Entity
@Table(name = "stem_unit_performance_indicator")
public class StemUnitPerformanceIndicator implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private long stemUnitPerformanceIndicatorId;
	private LegendSubCriteria legendSubCriteria;
	@JsonIgnore
	private StemUnit stemUnit;
	private String status;

	public StemUnitPerformanceIndicator() {
		super();
	}

	public StemUnitPerformanceIndicator(long stemUnitPerformanceIndicatorId,
			LegendSubCriteria legendSubCriteria, String status,
			StemUnit stemUnit) {
		super();
		this.stemUnitPerformanceIndicatorId = stemUnitPerformanceIndicatorId;
		this.legendSubCriteria = legendSubCriteria;
		this.stemUnit = stemUnit;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "stem_unit_performance_indicator_id", unique = true, nullable = false)
	public long getStemUnitPerformanceIndicatorId() {
		return stemUnitPerformanceIndicatorId;
	}

	public void setStemUnitPerformanceIndicatorId(
			long stemUnitPerformanceIndicatorId) {
		this.stemUnitPerformanceIndicatorId = stemUnitPerformanceIndicatorId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "legend_sub_criteria_id")
	public LegendSubCriteria getLegendSubCriteria() {
		return legendSubCriteria;
	}

	public void setLegendSubCriteria(LegendSubCriteria legendSubCriteria) {
		this.legendSubCriteria = legendSubCriteria;
	}	
	
	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return status;
	}	

	public void setStatus(String status) {
		this.status = status;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "stem_unit_id")
	public StemUnit getStemUnit() {
		return stemUnit;
	}

	public void setStemUnit(StemUnit stemUnit) {
		this.stemUnit = stemUnit;
	}

}
