package com.lp.model;

// default package
// Generated Jun 11, 2014 7:25:34 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Unit generated by hbm2java
 */
public class StemList implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5940790768471811123L;
	/**
	 * 
	 */
	private List<StemQuestions> stemQuestionList = new ArrayList<>();
	
	private List<StemUnitPerformanceIndicator> stemUnitPerformanceIndicator = new ArrayList<StemUnitPerformanceIndicator>();	
	
	private List<FormativeAssessmentsUnitWise> formativeAssessmentsUnitWise = new ArrayList<FormativeAssessmentsUnitWise>();
	
	public List<StemQuestions> getStemQuestionList() {
		return stemQuestionList;
	}
	public void setStemQuestionList(List<StemQuestions> stemQuestionList) {
		this.stemQuestionList = stemQuestionList;
	}
	public List<StemUnitPerformanceIndicator> getStemUnitPerformanceIndicator() {
		return stemUnitPerformanceIndicator;
	}
	public void setStemUnitPerformanceIndicator(
			List<StemUnitPerformanceIndicator> stemUnitPerformanceIndicator) {
		this.stemUnitPerformanceIndicator = stemUnitPerformanceIndicator;
	}
	public List<FormativeAssessmentsUnitWise> getFormativeAssessmentsUnitWise() {
		return formativeAssessmentsUnitWise;
	}
	public void setFormativeAssessmentsUnitWise(
			List<FormativeAssessmentsUnitWise> formativeAssessmentsUnitWise) {
		this.formativeAssessmentsUnitWise = formativeAssessmentsUnitWise;
	}	
}
