package com.lp.model;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Unit generated by hbm2java
 */
public class StemAnalytics implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5940790768471811123L;
	/**
	 * 
	 */
	private String stemArea1;
	
	private String stemArea2;
	
	private int percentage;
	
	private long value;
	
	private String strand;
	
	private String strategy;

	public String getStemArea1() {
		return stemArea1;
	}

	public void setStemArea1(String stemArea1) {
		this.stemArea1 = stemArea1;
	}

	public String getStemArea2() {
		return stemArea2;
	}

	public void setStemArea2(String stemArea2) {
		this.stemArea2 = stemArea2;
	}

	public int getPercentage() {
		return percentage;
	}

	public void setPercentage(int percentage) {
		this.percentage = percentage;
	}

	public long getValue() {
		return value;
	}

	public void setValue(long value) {
		this.value = value;
	}

	public String getStrand() {
		return strand;
	}

	public void setStrand(String strand) {
		this.strand = strand;
	}

	public String getStrategy() {
		return strategy;
	}

	public void setStrategy(String strategy) {
		this.strategy = strategy;
	}
}
