package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StudentCompositeChartValuesId generated by hbm2java
 */
@Embeddable
public class StudentCompositeProjectScoreId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long csId;
	private long studentId;

	public StudentCompositeProjectScoreId() {
	}

	public StudentCompositeProjectScoreId(long csId, long studentId) {
		this.csId = csId;
		this.studentId = studentId;
	}

	@Column(name = "cs_id", nullable = false)
	public long getCsId() {
		return this.csId;
	}

	public void setCsId(long csId) {
		this.csId = csId;
	}

	@Column(name = "student_id", nullable = false)
	public long getStudentId() {
		return this.studentId;
	}

	public void setStudentId(long studentId) {
		this.studentId = studentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentCompositeProjectScoreId))
			return false;
		StudentCompositeProjectScoreId castOther = (StudentCompositeProjectScoreId) other;

		return (this.getCsId() == castOther.getCsId())
				&& (this.getStudentId() == castOther.getStudentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCsId();
		result = 37 * result + (int) this.getStudentId();
		return result;
	}

}
