package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * StudentCompositeActivityScore generated by hbm2java
 */
@Entity
@Table(name = "student_composite_activity_score")
public class StudentCompositeActivityScore implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private StudentCompositeActivityScoreId id;
	@JsonManagedReference
	private Student student;
	@JsonManagedReference
	private AssignActivity assignActivity;
	private int score;
	@JsonManagedReference
	private AcademicGrades academicGrades;
	

	public StudentCompositeActivityScore() {
	}

	public StudentCompositeActivityScore(StudentCompositeActivityScoreId id,
			Student student, int score, AssignActivity assignActivity) {
		this.id = id;
		this.student = student;
		this.score = score;
		this.assignActivity = assignActivity;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "studentId", column = @Column(name = "student_id", nullable = false)),
			@AttributeOverride(name = "assignActivityId", column = @Column(name = "assign_activity_id", nullable = false, length = 30)) })
	public StudentCompositeActivityScoreId getId() {
		return this.id;
	}

	public void setId(StudentCompositeActivityScoreId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "student_id", nullable = false, insertable = false, updatable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "score", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "assign_activity_id", nullable = false, insertable = false, updatable = false)
	public AssignActivity getAssignActivity() {
		return assignActivity;
	}

	public void setAssignActivity(AssignActivity assignActivity) {
		this.assignActivity = assignActivity;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "academic_grade_id", nullable = false, insertable = false, updatable = false)
	public AcademicGrades getAcademicGrades() {
		return academicGrades;
	}

	public void setAcademicGrades(AcademicGrades academicGrades) {
		this.academicGrades = academicGrades;
	}

}
