package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student")
public class Student implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long studentId;
	@JsonManagedReference
	private UserRegistration userRegistration;
	@JsonManagedReference
	private HomeroomClasses homeroomClasses;
	@JsonManagedReference
	private Grade grade;
	private String gender;
	private Date dob;
	private Date createDate;
	private Date changeDate;
	private String gradeStatus;
	private Long studentScId;
	// transient attribute added for holding the reading skills files of the student -- Added by Lalitha 
	@Transient 
	private ArrayList<FilesLP> rsFiles;	
	 
	

	public Student() {
	}

	public Student(long studentId, UserRegistration userRegistration,
			Grade grade, String gender, Date dob, Date createDate,
			Date changeDate) {
		this.studentId = studentId;
		this.userRegistration = userRegistration;
		this.grade = grade;
		this.gender = gender;
		this.dob = dob;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	public Student(long studentId, UserRegistration userRegistration,
			HomeroomClasses homeroomClasses, Grade grade, String gender,
			Date dob, Date createDate, Date changeDate, String gradeStatus, Long studentScId) {
		this.studentId = studentId;
		this.userRegistration = userRegistration;
		this.homeroomClasses = homeroomClasses;
		this.grade = grade;
		this.gender = gender;
		this.dob = dob;
		this.createDate = createDate;
		this.changeDate = changeDate;
		this.gradeStatus = gradeStatus;
		this.studentScId = studentScId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "student_id", unique = true, nullable = false)
	public long getStudentId() {
		return this.studentId;
	}

	public void setStudentId(long studentId) {
		this.studentId = studentId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "reg_id", nullable = false)
	public UserRegistration getUserRegistration() {
		return this.userRegistration;
	}

	public void setUserRegistration(UserRegistration userRegistration) {
		this.userRegistration = userRegistration;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "homeroom_id")
	public HomeroomClasses getHomeroomClasses() {
		return this.homeroomClasses;
	}

	public void setHomeroomClasses(HomeroomClasses homeroomClasses) {
		this.homeroomClasses = homeroomClasses;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "grade_id", nullable = false)
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@Column(name = "gender", nullable = false, length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_date", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}
	
	@Column(name = "grade_status", nullable = false, length = 19)
	public String getGradeStatus() {
		return gradeStatus;
	}

	public void setGradeStatus(String gradeStatus) {
		this.gradeStatus = gradeStatus;
	}
	
	@Column(name = "student_sc_id", nullable = true)
	public Long getStudentScId() {
		return studentScId;
	}

	public void setStudentScId(Long studentScId) {
		this.studentScId = studentScId;
	}	
	
	@Transient
	public ArrayList<FilesLP> getRsFiles() {
		return rsFiles;
	}

	public void setRsFiles(ArrayList<FilesLP> rsFiles) {
		this.rsFiles = rsFiles;
	}

}
