package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * StudentCompositeLessonScore generated by hbm2java
 */
@Entity
@Table(name = "student_composite_lesson_score")
public class StudentCompositeLessonScore implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private StudentCompositeLessonScoreId id;
	@JsonManagedReference
	private Student student;
	@JsonManagedReference
	private AssignLessons assignLessons;
	private int score;
	@JsonManagedReference
	private AcademicGrades academicGrades;
	

	public StudentCompositeLessonScore() {
	}

	public StudentCompositeLessonScore(StudentCompositeLessonScoreId id,
			Student student, AssignLessons assignLessons, int score) {
		this.id = id;
		this.student = student;
		this.assignLessons = assignLessons;
		this.score = score;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "studentId", column = @Column(name = "student_id", nullable = false)),
			@AttributeOverride(name = "assignLessonId", column = @Column(name = "assign_lesson_id", nullable = false, length = 30)) })
	public StudentCompositeLessonScoreId getId() {
		return this.id;
	}

	public void setId(StudentCompositeLessonScoreId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "student_id", nullable = false, insertable = false, updatable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@Column(name = "score", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "assign_lesson_id", nullable = false, insertable = false, updatable = false)
	public AssignLessons getAssignLessons() {
		return assignLessons;
	}

	public void setAssignLessons(AssignLessons AssignLessons) {
		this.assignLessons = AssignLessons;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "academic_grade_id", nullable = false, insertable = false, updatable = false)
	public AcademicGrades getAcademicGrades() {
		return academicGrades;
	}

	public void setAcademicGrades(AcademicGrades academicGrades) {
		this.academicGrades = academicGrades;
	}

}
