//default package
//Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1
package com.lp.model;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
* RubricValues generated by hbm2java
*/
@Entity
@Table(name = "student_ptask_evidence")
public class StudentPtaskEvidence implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long studentPtaskEvidenceId;
	@JsonManagedReference
	private AssignedPtasks assignedPtasks;
	String evidenceDesc;
	@JsonManagedReference
	private PerformanceGroupStudents performanceGroupStudents;

	public StudentPtaskEvidence() {
	}

	public StudentPtaskEvidence(long studentPtaskEvidenceId,AssignedPtasks assignedPtasks,String evidenceDesc,PerformanceGroupStudents performanceGroupStudents) {
		this.studentPtaskEvidenceId = studentPtaskEvidenceId;
		this.assignedPtasks = assignedPtasks;
	    this.evidenceDesc=evidenceDesc;
	    this.performanceGroupStudents = performanceGroupStudents;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "student_ptask_evidence_id", unique = true, nullable = false)
	public long getStudentPtaskEvidenceId() {
		return this.studentPtaskEvidenceId;
	}

	public void setStudentPtaskEvidenceId(long studentPtaskEvidenceId) {
		this.studentPtaskEvidenceId = studentPtaskEvidenceId;
	}


	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "assigned_ptask_id", nullable = false)
	public AssignedPtasks getAssignedPtasks() {
		return this.assignedPtasks;
	}

	public void setAssignedPtasks(AssignedPtasks assignedPtasks) {
		this.assignedPtasks = assignedPtasks;
	}

	
	@Column(name = "evidence", nullable = false, length = 45)
	public String getEvidenceDesc() {
		return this.evidenceDesc;
	}

	public void setEvidenceDesc(String evidenceDesc) {
		this.evidenceDesc = evidenceDesc;
	}
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ptask_group_student_id", nullable = true)
	public PerformanceGroupStudents getPerformanceGroupStudents() {
		return this.performanceGroupStudents;
	}

	public void setPerformanceGroupStudents(PerformanceGroupStudents performanceGroupStudents) {
		this.performanceGroupStudents = performanceGroupStudents;
	}	


}
