package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StudentCompositeChartValuesId generated by hbm2java
 */
@Embeddable
public class StudentCompositeActivityScoreId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long studentId;
	private long assignActivityId;

	public StudentCompositeActivityScoreId() {
	}

	public StudentCompositeActivityScoreId(long studentId,
			long assignActivityId) {
		this.studentId = studentId;
		this.assignActivityId = assignActivityId;
	}

	@Column(name = "student_id", nullable = false)
	public long getStudentId() {
		return this.studentId;
	}

	public void setStudentId(long studentId) {
		this.studentId = studentId;
	}

	@Column(name = "assign_activity_id", nullable = false, length = 30)
	public long getAssignActivityId() {
		return this.assignActivityId;
	}

	public void setAssignActivityId(long assignActivityId) {
		this.assignActivityId = assignActivityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentCompositeActivityScoreId))
			return false;
		StudentCompositeActivityScoreId castOther = (StudentCompositeActivityScoreId) other;

		return (this.getStudentId() == castOther.getStudentId())
				&& (this.getAssignActivityId() == castOther.getAssignActivityId());
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + (int) this.getStudentId();
		result = 37 * result + (int) this.getAssignActivityId();
		return result;
	}

}
