package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * StudentCompositeProjectScore generated by hbm2java
 */
@Entity
@Table(name = "student_composite_project_score")
public class StudentCompositeProjectScore implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private StudentCompositeProjectScoreId id;
	@JsonManagedReference
	private Student student;
	@JsonManagedReference
	private ClassStatus classStatus;
	private int score;
	@JsonManagedReference
	private AcademicGrades academicGrades;

	public StudentCompositeProjectScore() {
	}

	public StudentCompositeProjectScore(StudentCompositeProjectScoreId id,
			Student student, ClassStatus classStatus, int score) {
		this.id = id;
		this.student = student;
		this.classStatus = classStatus;
		this.score = score;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "csId", column = @Column(name = "cs_id", nullable = false)),
			@AttributeOverride(name = "studentId", column = @Column(name = "student_id", nullable = false))})
	public StudentCompositeProjectScoreId getId() {
		return this.id;
	}

	public void setId(StudentCompositeProjectScoreId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "student_id", nullable = false, insertable = false, updatable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cs_id", nullable = false, insertable = false, updatable = false)
	public ClassStatus getClassStatus() {
		return this.classStatus;
	}

	public void setClassStatus(ClassStatus classStatus) {
		this.classStatus = classStatus;
	}

	@Column(name = "score", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "academic_grade_id", nullable = false, insertable = false, updatable = false)
	public AcademicGrades getAcademicGrades() {
		return academicGrades;
	}

	public void setAcademicGrades(AcademicGrades academicGrades) {
		this.academicGrades = academicGrades;
	}

}
