package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "syn_handler")
public class SynHandler implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private long synHandlerId;
	private long synContentId;
	@JsonManagedReference
	private UserRegistration userRegistration;
	@JsonBackReference
	List<SynHistoryHandler> synHistoryHandlerLt = new ArrayList<SynHistoryHandler>();
	private String status;
	
	public SynHandler() {
	}

		
	public SynHandler(long synHandlerId, long synContentId, UserRegistration userRegistration, String status) {
		super();
		this.synHandlerId = synHandlerId;
		this.synContentId = synContentId;
		this.userRegistration = userRegistration;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "syn_handler_id", unique = true, nullable = false)
	public long getSynHandlerId() {
		return synHandlerId;
	}


	public void setSynHandlerId(long synHandlerId) {
		this.synHandlerId = synHandlerId;
	}

	@Column(name = "syn_content_id", nullable = false)
	public long getSynContentId() {
		return synContentId;
	}


	public void setSynContentId(long synContentId) {
		this.synContentId = synContentId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_reg_id", nullable = false)
	public UserRegistration getUserRegistration() {
		return userRegistration;
	}


	public void setUserRegistration(UserRegistration userRegistration) {
		this.userRegistration = userRegistration;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "synHandler")
	public List<SynHistoryHandler> getSynHistoryHandlerLt() {
		return synHistoryHandlerLt;
	}


	public void setSynHistoryHandlerLt(List<SynHistoryHandler> synHistoryHandlerLt) {
		this.synHistoryHandlerLt = synHistoryHandlerLt;
	}
	
	
}
