package com.lp.model;

/**
 * Activity generated by hbm2java
 */
public class TaskForceResult implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long StudentId;
	private String firstName;
	private String lastName;
	private long wcpm;
	private long retellScore;
	private float accuracy;
	private float comprehension;
	private long checkFluencyGrade;
	private long checkComGrade;
	private String fluencyGraded = "not graded";
	private String comGraded = "not graded";;
	
	
	public long getStudentId() {
		return StudentId;
	}

	public void setStudentId(long studentId) {
		StudentId = studentId;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public long getWcpm() {
		return wcpm;
	}

	public void setWcpm(long wcpm) {
		this.wcpm = wcpm;
	}

	public long getRetellScore() {
		return retellScore;
	}

	public void setRetellScore(long retellScore) {
		this.retellScore = retellScore;
	}

	public float getAccuracy() {
		return accuracy;
	}

	public void setAccuracy(float accuracy) {
		this.accuracy = accuracy;
	}

	public float getComprehension() {
		return comprehension;
	}

	public void setComprehension(float comprehension) {
		this.comprehension = comprehension;
	}

	public long getCheckFluencyGrade() {
		return checkFluencyGrade;
	}

	public void setCheckFluencyGrade(long checkFluencyGrade) {
		this.checkFluencyGrade = checkFluencyGrade;
	}

	public long getCheckComGrade() {
		return checkComGrade;
	}

	public void setCheckComGrade(long checkComGrade) {
		this.checkComGrade = checkComGrade;
	}

	public String getFluencyGraded() {
		return fluencyGraded;
	}

	public void setFluencyGraded(String fluencyGraded) {
		this.fluencyGraded = fluencyGraded;
	}

	public String getComGraded() {
		return comGraded;
	}

	public void setComGraded(String comGraded) {
		this.comGraded = comGraded;
	}

}
