package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * TeacherSubjects generated by hbm2java
 */
@Entity
@Table(name = "teacher_subjects")
public class TeacherSubjects implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long teacherSubjectId;
	@JsonManagedReference
	private Teacher teacher;
	@JsonManagedReference
	private Grade grade;
	@JsonManagedReference
	private StudentClass studentClass;
	private Date createDate;
	private Date changeDate;
	@JsonManagedReference
	private GradeLevel gradeLevel;
	private int noSectionsPerDay;
	private int noSectionsPerWeek;
	private String otherSubjects;
	private String desktopStatus;
	private String requestedClassStatus;

	public TeacherSubjects() {
	}

	public TeacherSubjects(long teacherSubjectId, Teacher teacher, Grade grade,
			StudentClass studentClass, Date createDate, Date changeDate,
			GradeLevel gradeLevel, int noSectionsPerDay, int noSectionsPerWeek) {
		this.teacherSubjectId = teacherSubjectId;
		this.teacher = teacher;
		this.grade = grade;
		this.studentClass = studentClass;
		this.createDate = createDate;
		this.changeDate = changeDate;
		this.gradeLevel = gradeLevel;
		this.noSectionsPerDay = noSectionsPerDay;
		this.noSectionsPerWeek = noSectionsPerWeek;
	}

	public TeacherSubjects(long teacherSubjectId, Teacher teacher, Grade grade,
			StudentClass studentClass, Date createDate, Date changeDate,
			GradeLevel gradeLevel, int noSectionsPerDay, int noSectionsPerWeek,
			String otherSubjects, Long requestedClassId, String desktopStatus,
			String requestedClassStatus) {
		this.teacherSubjectId = teacherSubjectId;
		this.teacher = teacher;
		this.grade = grade;
		this.studentClass = studentClass;
		this.createDate = createDate;
		this.changeDate = changeDate;
		this.gradeLevel = gradeLevel;
		this.noSectionsPerDay = noSectionsPerDay;
		this.noSectionsPerWeek = noSectionsPerWeek;
		this.otherSubjects = otherSubjects;
		this.desktopStatus = desktopStatus;
		this.requestedClassStatus = requestedClassStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "teacher_subject_id", unique = true, nullable = false)
	public long getTeacherSubjectId() {
		return this.teacherSubjectId;
	}

	public void setTeacherSubjectId(long teacherSubjectId) {
		this.teacherSubjectId = teacherSubjectId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "teacher_id", nullable = false, insertable = true, updatable = true)
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "grade_id", nullable = false, insertable = true, updatable = true)
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "class_id", nullable = false, insertable = true, updatable = true)
	public StudentClass getStudentClass() {
		return this.studentClass;
	}

	public void setStudentClass(StudentClass studentClass) {
		this.studentClass = studentClass;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_date", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "grade_level_id", nullable = false, insertable = true, updatable = true)
	public GradeLevel getGradeLevel() {
		return this.gradeLevel;
	}

	public void setGradeLevel(GradeLevel gradeLevel) {
		this.gradeLevel = gradeLevel;
	}

	@Column(name = "no_sections_per_day", nullable = false)
	public int getNoSectionsPerDay() {
		return this.noSectionsPerDay;
	}

	public void setNoSectionsPerDay(int noSectionsPerDay) {
		this.noSectionsPerDay = noSectionsPerDay;
	}

	@Column(name = "no_sections_per_week", nullable = false)
	public int getNoSectionsPerWeek() {
		return this.noSectionsPerWeek;
	}

	public void setNoSectionsPerWeek(int noSectionsPerWeek) {
		this.noSectionsPerWeek = noSectionsPerWeek;
	}

	@Column(name = "other_subjects", length = 25)
	public String getOtherSubjects() {
		return this.otherSubjects;
	}

	public void setOtherSubjects(String otherSubjects) {
		this.otherSubjects = otherSubjects;
	}

	@Column(name = "desktop_status", length = 20)
	public String getDesktopStatus() {
		return this.desktopStatus;
	}

	public void setDesktopStatus(String desktopStatus) {
		this.desktopStatus = desktopStatus;
	}

	@Column(name = "requested_class_status", length = 20)
	public String getRequestedClassStatus() {
		return this.requestedClassStatus;
	}

	public void setRequestedClassStatus(String requestedClassStatus) {
		this.requestedClassStatus = requestedClassStatus;
	}

}
