package com.lp.model;
// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Teacher generated by hbm2java
 */
@Entity
@Table(name = "teacher")
public class Teacher implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long teacherId;
	@JsonManagedReference
	private UserRegistration userRegistration;
	private String status;
	private Long teacherScId;

	public Teacher() {
	}

	public Teacher(long teacherId) {
		this.teacherId = teacherId;
	}

	public Teacher(long teacherId, UserRegistration userRegistration,
			String status, long teacherScId) {
		this.teacherId = teacherId;
		this.userRegistration = userRegistration;
		this.status = status;
		this.teacherScId = teacherScId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "teacher_id", unique = true, nullable = false)
	public long getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(long teacherId) {
		this.teacherId = teacherId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "reg_id")
	public UserRegistration getUserRegistration() {
		return this.userRegistration;
	}

	public void setUserRegistration(UserRegistration userRegistration) {
		this.userRegistration = userRegistration;
	}

	@Column(name = "status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	@Column(name = "teacher_sc_id", nullable = true)
	public Long getTeacherScId() {
		return teacherScId;
	}

	public void setTeacherScId(Long teacherScId) {
		this.teacherScId = teacherScId;
	}
}
