package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * TeacherPerformances generated by hbm2java
 */
@Entity
@Table(name = "teacher_performances")
public class TeacherPerformances implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	@NotNull
	@Size(min = 1, max = 100)
	private String performance;

	public TeacherPerformances() {
	}

	public TeacherPerformances(long id) {
		this.id = id;
	}

	public TeacherPerformances(long id, String performance
			) {
		this.id = id;
		this.performance = performance;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "performance", length = 100)
	public String getPerformance() {
		return this.performance;
	}

	public void setPerformance(String performance) {
		this.performance = performance;
	}
}
