package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AdminTeacherReports generated by hbm2java
 */
@Entity
@Table(name = "teacher_reports")
public class TeacherReports implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long teacherReportId;
	@JsonManagedReference
	private AdminTeacherReports adminTeacherReports;
	@JsonManagedReference
	private TeacherPerformances teacherPerformances;
	private String choosenOption;
	private String comments;

	public TeacherReports() {
	}

	public TeacherReports(long teacherReportId,
			AdminTeacherReports adminTeacherReports) {
		this.teacherReportId = teacherReportId;
		this.adminTeacherReports = adminTeacherReports;
	}

	public TeacherReports(long teacherReportId,
			AdminTeacherReports adminTeacherReports,
			TeacherPerformances teacherPerformances, String choosenOption,
			String comments) {
		this.teacherReportId = teacherReportId;
		this.adminTeacherReports = adminTeacherReports;
		this.teacherPerformances = teacherPerformances;
		this.choosenOption = choosenOption;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "report_id", unique = true, nullable = false)
	public long getTeacherReportId() {
		return this.teacherReportId;
	}

	public void setTeacherReportId(long teacherReportId) {
		this.teacherReportId = teacherReportId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "performance_id")
	public TeacherPerformances getTeacherPerformances() {
		return this.teacherPerformances;
	}

	public void setTeacherPerformances(TeacherPerformances teacherPerformances) {
		this.teacherPerformances = teacherPerformances;
	}

	@Column(name = "choosen_option", length = 20)
	public String getChoosenOption() {
		return this.choosenOption;
	}

	public void setChoosenOption(String choosenOption) {
		this.choosenOption = choosenOption;
	}

	@Column(name = "comments", length = 200)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "admin_teacher_report_id")
	public AdminTeacherReports getAdminTeacherReports() {
		return this.adminTeacherReports;
	}

	public void setAdminTeacherReports(AdminTeacherReports adminTeacherReports) {
		this.adminTeacherReports = adminTeacherReports;
	}
}
