package com.lp.model;

// default package
// Generated Jun 11, 2014 7:25:34 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Unit generated by hbm2java
 */
@Entity
@Table(name = "unit")
public class Unit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long unitId;
	private Long unitNo;
	private String unitName;
	@JsonManagedReference
	private GradeClasses gradeClasses;
	@JsonManagedReference
	private UserRegistration userRegistration;
	//@NotNull
	//@Size(min = 1, max = 45)
	private Date createDate;
	private Date changeDate;
	
	@Transient
	private List<Lesson> lessonsList = new ArrayList<Lesson>(0);
	

	public Unit() {
	}

	public Unit(Long unitNo, String unitName, GradeClasses gradeClass,
			UserRegistration userRegistration,Date createDate,
			Date changeDate
			) {
		this.unitNo = unitNo;
		this.unitName = unitName;
		this.gradeClasses = gradeClass;
		this.userRegistration = userRegistration;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "unit_id", unique = true, nullable = false)
	public Long getUnitId() {
		return this.unitId;
	}

	public void setUnitId(Long unitId) {
		this.unitId = unitId;
	}

	@Column(name = "unit_no")
	public Long getUnitNo() {
		return this.unitNo;
	}

	public void setUnitNo(Long unitNo) {
		this.unitNo = unitNo;
	}

	@Column(name = "unit_name", length = 45)
	public String getUnitName() {
		return this.unitName;
	}

	public void setUnitName(String unitName) {
		this.unitName = unitName;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "grade_class_id")
	public GradeClasses getGradeClasses() {
		return gradeClasses;
	}

	public void setGradeClasses(GradeClasses gradeClasses) {
		this.gradeClasses = gradeClasses;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "created_by")
	public UserRegistration getUserRegistration() {
		return userRegistration;
	}

	public void setUserRegistration(UserRegistration userRegistration) {
		this.userRegistration = userRegistration;
	}
	
	@Transient
	public List<Lesson> getLessonsList() {
		return lessonsList;
	}

	public void setLessonsList(List<Lesson> lessonsList) {
		this.lessonsList = lessonsList;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_date", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

}
