package com.lp.model;

// default package
// Generated May 29, 2014 7:37:08 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * UserRegistration generated by hbm2java
 */
@Entity
@Table(name = "user_registration")
public class UserRegistration implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long regId;
	@JsonManagedReference
	private Address address;
	@JsonManagedReference
	private User user;
	@JsonManagedReference
	private School school;
	private String title;
	private String firstName;
	private String lastName;
	private String password;
	private String qualification;
	private String phonenumber;
	private String emailId;
	private String ssoUserName;
	private Long parentRegId;
	private Long parentRegId2;
	private Date createDate;
	private Date changeDate;
	private String experience;
	private String subjects;
	private String interestareas;
	private String projects;
	private String education;
	private String contactinfo;
	private District district;
	private String status;
	@Transient
	private String parentEmailId;
	@Transient
	private String verificationCode;
	@Transient
	private String address1;
	@Transient
	private String address2;
	@Transient
	private String newPassword;
	@Transient
	private String confirmPassword;
	@Transient
	private String countryId;
	@Transient
	private String stateId;
	@Transient
	private String city;
	@Transient
	private String zipcode;
	@Transient
	private String securityQuestionId;
	@Transient
	private String answer;
	@Transient
	private String schoolId;
	@Transient
	private String gradeId;
	@Transient
	private long districtId;
	@Transient
	private long sportId;
	@Transient
	private String newUserName;
	@Transient
	private Long teacherScId;
	

	public UserRegistration() {
	}

	public UserRegistration(long regId, User user, String emailId,
			School school, Date createDate, Date changeDate) {
		this.regId = regId;
		this.user = user;
		this.emailId = emailId;
		this.school = school;
		this.createDate = createDate;
		this.changeDate = changeDate;
	}

	public UserRegistration(long regId, Address address, User user,
			School school, String title, String firstName, String lastName,
			String password, String qualification, String phonenumber,
			String emailId, Long parentRegId,Long parentRegId2, Date createDate, Date changeDate,
			String experience, String subjects, String interestareas,
			String projects, String education, String contactinfo, String ssoUserName) {
		this.regId = regId;
		this.address = address;
		this.user = user;
		this.school = school;
		this.title = title;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.qualification = qualification;
		this.phonenumber = phonenumber;
		this.emailId = emailId;
		this.parentRegId = parentRegId;
		this.parentRegId2 = parentRegId2;
		this.createDate = createDate;
		this.changeDate = changeDate;
		this.experience = experience;
		this.subjects = subjects;
		this.interestareas = interestareas;
		this.projects = projects;
		this.education = education;
		this.contactinfo = contactinfo;
		this.ssoUserName = ssoUserName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "reg_id", unique = true, nullable = false)
	public long getRegId() {
		return this.regId;
	}

	public void setRegId(long regId) {
		this.regId = regId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "address_id")
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_typeid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "school_id")
	public School getSchool() {
		return school;
	}

	public void setSchool(School school) {
		this.school = school;
	}

	@Column(name = "title", length = 5)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "first_name", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "qualification", length = 200)
	public String getQualification() {
		return this.qualification;
	}

	public void setQualification(String qualification) {
		this.qualification = qualification;
	}

	@Column(name = "phonenumber")
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "email_id", nullable = false, length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}
	
	@Column(name = "sso_username", nullable = false, length = 80)
	public String getSsoUserName() {
		return ssoUserName;
	}

	public void setSsoUserName(String ssoUserName) {
		this.ssoUserName = ssoUserName;
	}

	@Column(name = "parent_reg_id")
	public Long getParentRegId() {
		return this.parentRegId;
	}

	public void setParentRegId(Long parentRegId) {
		this.parentRegId = parentRegId;
	}
	
	@Column(name = "parent_reg_id2")
	public Long getParentRegId2() {
		return this.parentRegId2;
	}

	public void setParentRegId2(Long parentRegId2) {
		this.parentRegId2 = parentRegId2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "change_date", nullable = false, length = 19)
	public Date getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	@Column(name = "experience", length = 250)
	public String getExperience() {
		return this.experience;
	}

	public void setExperience(String experience) {
		this.experience = experience;
	}

	@Column(name = "subjects", length = 250)
	public String getSubjects() {
		return this.subjects;
	}

	public void setSubjects(String subjects) {
		this.subjects = subjects;
	}

	@Column(name = "interestareas", length = 250)
	public String getInterestareas() {
		return this.interestareas;
	}

	public void setInterestareas(String interestareas) {
		this.interestareas = interestareas;
	}

	@Column(name = "projects", length = 250)
	public String getProjects() {
		return this.projects;
	}

	public void setProjects(String projects) {
		this.projects = projects;
	}

	@Column(name = "education", length = 250)
	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	@Column(name = "contactinfo", length = 250)
	public String getContactinfo() {
		return this.contactinfo;
	}

	public void setContactinfo(String contactinfo) {
		this.contactinfo = contactinfo;
	}

	@Transient
	public String getParentEmailId() {
		return parentEmailId;
	}

	public void setParentEmailId(String parentEmailId) {
		this.parentEmailId = parentEmailId;
	}

	@Transient
	public String getVerificationCode() {
		return verificationCode;
	}

	public void setVerificationCode(String verificationCode) {
		this.verificationCode = verificationCode;
	}

	@Transient
	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Transient
	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Transient
	public String getNewPassword() {
		return newPassword;
	}

	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}

	@Transient
	public String getConfirmPassword() {
		return confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	@Transient
	public String getCountryId() {
		return countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	@Transient
	public String getStateId() {
		return stateId;
	}

	public void setStateId(String stateId) {
		this.stateId = stateId;
	}

	@Transient
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Transient
	public String getZipcode() {
		return zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Transient
	public String getSecurityQuestionId() {
		return securityQuestionId;
	}

	public void setSecurityQuestionId(String securityQuestionId) {
		this.securityQuestionId = securityQuestionId;
	}

	@Transient
	public String getAnswer() {
		return answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Transient
	public String getSchoolId() {
		return schoolId;
	}

	public void setSchoolId(String schoolId) {
		this.schoolId = schoolId;
	}

	@Transient
	public long getSportId() {
		return sportId;
	}

	public void setSportId(long sportId) {
		this.sportId = sportId;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "district_id")
	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	@Transient
	public long getdistrictId() {
		return districtId;
	}

	public void setdistrictId(long districtId) {
		this.districtId = districtId;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Transient
	public String getGradeId() {
		return gradeId;
	}

	public void setGradeId(String gradeId) {
		this.gradeId = gradeId;
	}
	@Transient
	public String getNewUserName() {
		return newUserName;
	}

	public void setNewUserName(String newUserName) {
		this.newUserName = newUserName;
	}
	@Transient
	public Long getTeacherScId() {
		return teacherScId;
	}

	public void setTeacherScId(Long teacherScId) {
		this.teacherScId = teacherScId;
	}
}
